"""
Tests for the Community AI artifact stripper.

Verifies that AI provenance markers are removed from docstrings and attribution
dunders, that legitimate documentation / data is left intact, and that stripped
code still compiles and runs. Tests compile+exec the transformed AST directly,
so they run identically on Python 3.8-3.14.
"""

import ast

import pytest

from pyobfus.config import ObfuscationConfig
from pyobfus.transformers.ai_artifact_stripper import AIArtifactStripper


def _strip(source: str, enabled: bool = True):
    """Transform source, return (new_tree, transformer)."""
    config = ObfuscationConfig.community_edition()
    config.strip_ai_artifacts = enabled
    tree = ast.parse(source)
    transformer = AIArtifactStripper(config)
    new_tree = transformer.transform(tree)
    return new_tree, transformer


def _strings_in(tree: ast.AST):
    """All str constants present in the tree (for assertion convenience)."""
    return [
        n.value for n in ast.walk(tree) if isinstance(n, ast.Constant) and isinstance(n.value, str)
    ]


def _run(tree: ast.AST) -> dict:
    code = compile(tree, "<strip>", "exec")
    ns: dict = {}
    exec(code, ns)  # noqa: S102 - executing our own transformed AST in tests
    return ns


# --------------------------------------------------------------------------- #
# Docstring removal
# --------------------------------------------------------------------------- #


def test_module_docstring_with_marker_removed():
    tree, t = _strip('"""Module.\n\n\U0001f916 Generated with Claude Code.\n"""\nx = 1')
    assert all("Generated with Claude" not in s for s in _strings_in(tree))
    assert t.get_statistics()["docstrings_stripped"] == 1
    assert _run(tree)["x"] == 1


def test_function_docstring_with_marker_removed_body_preserved():
    src = "def f():\n" '    "Fetch a user. Generated by Claude."\n' "    return 42\n"
    tree, t = _strip(src)
    assert all("Generated by Claude" not in s for s in _strings_in(tree))
    assert t.get_statistics()["docstrings_stripped"] == 1
    assert _run(tree)["f"]() == 42


def test_function_with_only_ai_docstring_gets_pass():
    """If removing the docstring empties the body, a `pass` is inserted."""
    tree, _ = _strip('def f():\n    "Generated by Copilot."\n')
    func = tree.body[0]
    assert isinstance(func, ast.FunctionDef)
    assert len(func.body) == 1
    assert isinstance(func.body[0], ast.Pass)
    # still callable
    assert _run(tree)["f"]() is None


def test_class_docstring_with_marker_removed():
    src = 'class C:\n    "Service. Co-Authored-By: Claude"\n    value = 7\n'
    tree, t = _strip(src)
    assert all("Co-Authored-By" not in s for s in _strings_in(tree))
    assert t.get_statistics()["docstrings_stripped"] == 1
    assert _run(tree)["C"].value == 7


# --------------------------------------------------------------------------- #
# Attribution dunder removal
# --------------------------------------------------------------------------- #


def test_author_dunder_with_marker_removed():
    tree, t = _strip('__author__ = "Generated by Claude"\nx = 5')
    ns = _run(tree)
    assert "__author__" not in ns
    assert ns["x"] == 5
    assert t.get_statistics()["attributions_stripped"] == 1


@pytest.mark.parametrize(
    "dunder", ["__copyright__", "__credits__", "__maintainer__", "__authors__"]
)
def test_other_attribution_dunders_removed(dunder):
    tree, t = _strip(f'{dunder} = "made with cursor"\nkeep = 1')
    ns = _run(tree)
    assert dunder not in ns
    assert ns["keep"] == 1


def test_annotated_author_dunder_removed():
    tree, t = _strip('__author__: str = "written by Copilot"\nx = 1')
    ns = _run(tree)
    assert "__author__" not in ns
    assert ns["x"] == 1
    assert t.get_statistics()["attributions_stripped"] == 1


# --------------------------------------------------------------------------- #
# Marker pattern coverage
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "marker",
    [
        "Generated by Claude",
        "generated with copilot",
        "Generated by ChatGPT",
        "Generated by GPT",
        "Co-Authored-By: Claude",
        "Coauthored by AI",
        "written by Cursor",
        "made with Gemini",
        "This uses Claude Code under the hood",
        "\U0001f916 Generated with something",
    ],
)
def test_marker_variants_detected(marker):
    tree, t = _strip(f'def f():\n    "{marker}"\n    return 1\n')
    assert t.get_statistics()["docstrings_stripped"] == 1
    assert _run(tree)["f"]() == 1


# --------------------------------------------------------------------------- #
# Must NOT remove legitimate content
# --------------------------------------------------------------------------- #


def test_legit_docstring_preserved():
    src = 'def add(a, b):\n    "Return the sum of a and b."\n    return a + b\n'
    tree, t = _strip(src)
    assert "Return the sum of a and b." in _strings_in(tree)
    assert t.get_statistics()["docstrings_stripped"] == 0
    assert _run(tree)["add"](2, 3) == 5


def test_legit_author_dunder_preserved():
    tree, t = _strip('__author__ = "Jane Doe"\nx = 1')
    ns = _run(tree)
    assert ns["__author__"] == "Jane Doe"
    assert t.get_statistics()["attributions_stripped"] == 0


def test_arbitrary_string_literal_not_touched():
    """A regular (non-dunder) assignment is data, not metadata — leave it."""
    tree, t = _strip('note = "Generated by Claude"\nresult = note.upper()')
    ns = _run(tree)
    assert ns["note"] == "Generated by Claude"
    assert ns["result"] == "GENERATED BY CLAUDE"
    assert t.get_statistics()["attributions_stripped"] == 0
    assert t.get_statistics()["docstrings_stripped"] == 0


def test_marker_inside_print_call_not_touched():
    tree, _ = _strip('def show():\n    return "Generated by Claude"\n')
    # the return value is program data, must survive
    assert _run(tree)["show"]() == "Generated by Claude"


def test_disabled_by_default_is_noop():
    src = '"""\U0001f916 Generated with Claude Code."""\n__author__ = "Generated by Claude"\nx = 1'
    tree, t = _strip(src, enabled=False)
    ns = _run(tree)
    assert ns["__author__"] == "Generated by Claude"
    assert t.get_statistics()["docstrings_stripped"] == 0
    assert t.get_statistics()["attributions_stripped"] == 0


# --------------------------------------------------------------------------- #
# Combined / realistic
# --------------------------------------------------------------------------- #


def test_realistic_module_round_trip():
    src = (
        '"""User service.\n\n\U0001f916 Generated with Claude Code. Here is the implementation.\n"""\n'
        '__author__ = "Generated by Claude"\n'
        '__version__ = "1.0"\n'
        "\n"
        "def get_user(uid):\n"
        '    "Fetch a user by id. Generated by Claude."\n'
        "    label = 'AI-generated stub'\n"
        "    return {'id': uid, 'note': label}\n"
    )
    tree, t = _strip(src)
    ns = _run(tree)

    # AI markers gone from docstrings + dunders
    assert "__author__" not in ns
    assert ns["__version__"] == "1.0"  # legit dunder kept
    # arbitrary string data preserved
    assert ns["get_user"](9) == {"id": 9, "note": "AI-generated stub"}

    stats = t.get_statistics()
    assert stats["docstrings_stripped"] == 2  # module + function
    assert stats["attributions_stripped"] == 1  # __author__


def test_statistics_shape():
    tree, t = _strip('def f():\n    "Generated by Claude"\n    return 1\n')
    stats = t.get_statistics()
    assert set(stats) == {"docstrings_stripped", "attributions_stripped", "transformations"}
    assert stats["transformations"] == 1
