"""Regression tests for two related pre-existing bugs:

1. **Cross-file (default directory) mode silently dropped every content-level
   transform.** ``pyobfus src/ -o dist/`` went through the
   ``CrossFileOrchestrator``, which only applied name/import mapping and never
   ran string encoding, numeric obfuscation, AI-marker stripping, control-flow
   flattening, string encryption, anti-debug or dead-code. The build exited 0
   with ``status: success`` and no warning, so ``--string-encryption`` and the
   ``commercial``/``library`` presets became no-ops on directories.

2. **Every Pro preset degraded to community output unless ``--level pro`` was
   also passed.** ``config.level = level`` unconditionally overwrote a preset's
   ``level="pro"`` with the ``--level`` default, so ``--preset commercial``
   (advertised as "maximum protection") produced only name-mangled output. The
   ``--level`` flag is now tri-state (see issue #25 for the same fix applied to
   ``--remove-docstrings`` et al.).

Both paths are now routed through ``pyobfus.core.content_transforms`` so the
single-file and cross-file pipelines cannot diverge again.
"""

import ast
import json
import subprocess
import sys

import pytest
from unittest.mock import patch
from click.testing import CliRunner

from pyobfus.cli import main

try:
    import pyobfus_pro  # noqa: F401

    PRO_AVAILABLE = True
except ImportError:
    PRO_AVAILABLE = False

requires_pro = pytest.mark.skipif(not PRO_AVAILABLE, reason="pyobfus_pro not installed")


@pytest.fixture
def runner():
    return CliRunner()


def _project(tmp_path):
    src = tmp_path / "src"
    src.mkdir()
    (src / "mathlib.py").write_text(
        '"""Generated by Claude."""\n'
        "MULTIPLIER = 42\n"
        "def compute(x):\n"
        "    return x * MULTIPLIER + 100\n"
    )
    (src / "main.py").write_text(
        '"""Co-Authored-By: Claude"""\n'
        "from mathlib import compute\n"
        "def entry():\n"
        "    return compute(3)\n"
    )
    return src


def _run_json(runner, args):
    result = runner.invoke(main, args)
    assert result.exit_code == 0, result.output
    return result, json.loads(result.output)


class TestCrossFileCommunityContentTransforms:
    """Community content transforms must apply in default cross-file dir mode."""

    def test_numeric_obfuscation_applies_in_directory_mode(self, runner, tmp_path):
        src = _project(tmp_path)
        out = tmp_path / "out"
        _result, payload = _run_json(
            runner, [str(src), "-o", str(out), "--numeric-obfuscation", "--json"]
        )
        assert payload["status"] == "success"
        assert payload["stats"]["numbers_obfuscated"] > 0
        # The obfuscator replaces each integer literal with a random,
        # value-preserving expression (e.g. ``42`` -> ``(42 ^ k) ^ k``), so the
        # source constants must be gone. Assert on the *parsed AST* rather than
        # the raw text: a random 32-bit XOR/add/sub component can itself begin
        # with the digits "42"/"100", which would make a substring check flake.
        module = ast.parse((out / "mathlib.py").read_text())
        int_literals = {
            n.value
            for n in ast.walk(module)
            if isinstance(n, ast.Constant)
            and isinstance(n.value, int)
            and not isinstance(n.value, bool)
        }
        assert 42 not in int_literals
        assert 100 not in int_literals

    def test_strip_ai_artifacts_applies_in_directory_mode(self, runner, tmp_path):
        src = _project(tmp_path)
        out = tmp_path / "out"
        _result, payload = _run_json(
            runner, [str(src), "-o", str(out), "--strip-ai-artifacts", "--json"]
        )
        assert payload["stats"]["ai_docstrings_stripped"] > 0
        assert "Generated by Claude" not in (out / "mathlib.py").read_text()
        assert "Co-Authored-By: Claude" not in (out / "main.py").read_text()

    def test_transforms_apply_to_every_file(self, runner, tmp_path):
        src = _project(tmp_path)
        out = tmp_path / "out"
        _run_json(runner, [str(src), "-o", str(out), "--numeric-obfuscation", "--json"])
        # Both modules carry numeric literals; neither should keep them verbatim.
        assert "* MULTIPLIER + 100" not in (out / "mathlib.py").read_text()
        assert "compute(3)" not in (out / "main.py").read_text()


class TestCrossFileParityWithSingleFile:
    """A single file obfuscated via dir mode and directly must both transform."""

    def test_single_file_and_directory_both_strip(self, runner, tmp_path):
        src = tmp_path / "s"
        src.mkdir()
        (src / "m.py").write_text('"""Generated by Claude."""\nX = 7\n')

        out_dir = tmp_path / "od"
        _run_json(runner, [str(src), "-o", str(out_dir), "--strip-ai-artifacts", "--json"])
        out_single = tmp_path / "single.py"
        _run_json(
            runner,
            [str(src / "m.py"), "-o", str(out_single), "--strip-ai-artifacts", "--json"],
        )
        assert "Generated by Claude" not in (out_dir / "m.py").read_text()
        assert "Generated by Claude" not in out_single.read_text()


@requires_pro
class TestProPresetLevelSurvives:
    """A Pro preset must keep level=pro without an explicit --level pro."""

    @patch("pyobfus.cli.is_trial_active", return_value=True)
    def test_commercial_preset_single_file_applies_pro(self, _trial, runner, tmp_path):
        src = tmp_path / "m.py"
        src.write_text("def f(x):\n    if x:\n        return 1\n    return 0\n")
        out = tmp_path / "out.py"
        _result, payload = _run_json(
            runner, [str(src), "-o", str(out), "--preset", "commercial", "--json"]
        )
        assert payload["level"] == "pro"
        # commercial => control_flow_flattening + dead_code + anti_debug
        stats = payload["stats"]
        assert stats.get("control_flow_applied", 0) > 0
        assert stats.get("anti_debug_checks", 0) > 0

    @patch("pyobfus.cli.is_trial_active", return_value=True)
    def test_commercial_preset_directory_applies_pro(self, _trial, runner, tmp_path):
        src = _project(tmp_path)
        out = tmp_path / "out"
        _result, payload = _run_json(
            runner, [str(src), "-o", str(out), "--preset", "commercial", "--json"]
        )
        assert payload["level"] == "pro"
        assert payload["stats"].get("control_flow_applied", 0) > 0

    @patch("pyobfus.cli.is_trial_active", return_value=True)
    def test_explicit_level_pro_still_wins(self, _trial, runner, tmp_path):
        # Passing --level pro on a community-default run still forces pro.
        src = tmp_path / "m.py"
        src.write_text("def f(x):\n    return x + 1\n")
        out = tmp_path / "out.py"
        _result, payload = _run_json(
            runner, [str(src), "-o", str(out), "--level", "pro", "--control-flow", "--json"]
        )
        assert payload["level"] == "pro"


@requires_pro
class TestCrossFileProRuntimeCorrectness:
    """Obfuscated cross-file Pro output must still import and run correctly."""

    @patch("pyobfus.cli.is_trial_active", return_value=True)
    def test_obfuscated_project_executes(self, _trial, runner, tmp_path):
        src = _project(tmp_path)
        out = tmp_path / "out"
        _run_json(runner, [str(src), "-o", str(out), "--preset", "library", "--json"])
        # Run the obfuscated project in a fresh interpreter and confirm the
        # cross-module call still yields 3 * 42 + 100 == 226.
        script = (
            "import sys; sys.path.insert(0, %r); import main; "
            "vals=[getattr(main,n)() for n in dir(main) "
            "if callable(getattr(main,n)) and getattr(getattr(main,n),'__module__',None)=='main' "
            "and not n.startswith('__')]; print(226 in vals)" % str(out)
        )
        proc = subprocess.run(
            [sys.executable, "-c", script], capture_output=True, text=True, timeout=60
        )
        assert proc.returncode == 0, proc.stderr
        assert "True" in proc.stdout
