"""
Command-line interface for pyobfus.

Provides a user-friendly CLI for obfuscating Python files and projects.
"""

import io
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import click

from pyobfus import __version__
from pyobfus.config import ObfuscationConfig
from pyobfus.constants import (
    GITHUB_REPO,
    PRO_PRICE_USD,
    STRIPE_PAYMENT_LINK,
    TRACE_MARKER_PREFIX,
)
from pyobfus.config_templates import get_template, list_templates
from pyobfus.config_validator import validate_config_file, find_config_file
from pyobfus.core.analyzer import SymbolAnalyzer
from pyobfus.core.generator import CodeGenerator
from pyobfus.core.parser import ASTParser
from pyobfus.core.orchestrator import CrossFileOrchestrator
from pyobfus.exceptions import LimitExceededError, PyObfusError
from pyobfus.transformers.name_mangler import NameMangler
from pyobfus.utils import filter_python_files
from pyobfus.trial import is_trial_active, get_trial_expiry_message

# Check if Pro edition is available
try:
    import pyobfus_pro  # type: ignore[import]

    PRO_AVAILABLE = True
except ImportError:
    pyobfus_pro = None  # type: ignore[assignment]
    PRO_AVAILABLE = False

# v0.5.1 build-fusion helper (orchestrates the patent-targeted Pro source passes)
try:
    from pyobfus_pro import build_fusion as _build_fusion  # type: ignore[import]
except ImportError:
    _build_fusion = None  # type: ignore[assignment]


@click.command()
@click.argument("input_path", type=click.Path(exists=True), required=False)
@click.option(
    "-o",
    "--output",
    "output_path",
    type=click.Path(),
    help="Output file or directory path",
)
@click.option(
    "-c",
    "--config",
    "config_path",
    type=click.Path(exists=True),
    help="Configuration file (YAML)",
)
@click.option(
    "--init-config",
    "init_config_template",
    type=click.Choice(["django", "flask", "library", "general"], case_sensitive=False),
    help="Generate configuration template (django, flask, library, general)",
)
@click.option(
    "--validate-config",
    "validate_config_path",
    type=click.Path(exists=True),
    help="Validate a configuration file",
)
@click.option(
    "--level",
    type=click.Choice(["community", "pro"], case_sensitive=False),
    default="community",
    help="Obfuscation level (default: community)",
)
@click.option(
    "--remove-docstrings/--keep-docstrings",
    default=True,
    help="Remove docstrings (default: remove)",
)
@click.option(
    "--remove-comments/--keep-comments",
    default=True,
    help="Remove comments (default: remove)",
)
@click.option(
    "--name-prefix",
    default="I",
    help="Prefix for obfuscated names (default: I)",
)
@click.option(
    "--preserve-param-names",
    is_flag=True,
    help="Preserve parameter names to allow keyword arguments after obfuscation",
)
@click.option(
    "--numeric-obfuscation",
    is_flag=True,
    help="Replace numeric literals with equivalent opaque expressions (Community feature)",
)
@click.option(
    "--strip-ai-artifacts",
    is_flag=True,
    help="Remove AI provenance markers (e.g. 'Generated by Claude') from "
    "docstrings and attribution dunders (Community feature)",
)
@click.option(
    "--verbose",
    "-v",
    is_flag=True,
    help="Verbose output",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Preview obfuscation without writing output",
)
@click.option(
    "--cross-file/--no-cross-file",
    default=True,
    help="Enable cross-file import mapping (default: enabled)",
)
@click.option(
    "--upgrade",
    is_flag=True,
    help="Show Pro edition features and purchase information",
)
@click.option(
    "--control-flow",
    is_flag=True,
    help="Enable control flow flattening (Pro feature)",
)
@click.option(
    "--string-encryption",
    is_flag=True,
    help="Enable AES-256 string encryption (Pro feature)",
)
@click.option(
    "--anti-debug",
    is_flag=True,
    help="Enable anti-debugging protection (Pro feature)",
)
@click.option(
    "--dead-code",
    is_flag=True,
    help="Enable dead code injection (Pro feature)",
)
@click.option(
    "--expire",
    type=str,
    help="Set expiration date for obfuscated code (YYYY-MM-DD format, Pro feature)",
)
@click.option(
    "--bind-machine",
    is_flag=True,
    help="Bind obfuscated code to current machine (Pro feature)",
)
@click.option(
    "--max-runs",
    type=int,
    default=0,
    help="Set maximum run count for obfuscated code (0=unlimited, Pro feature)",
)
@click.option(
    "--selective-opacity",
    is_flag=True,
    help="Encrypt @opacity(Layer.ENCRYPTED) functions with AES-256-GCM (Pro, v0.5.1)",
)
@click.option(
    "--seal-code",
    is_flag=True,
    help="Bytecode integrity seal for @seal_code functions (Pro, v0.5.1)",
)
@click.option(
    "--vault",
    "vault_flag",
    is_flag=True,
    help="Encrypt vault_secrets({...}) into a runtime String Vault (Pro, v0.5.1)",
)
@click.option(
    "--scrub-traceback",
    is_flag=True,
    help="Encrypt production tracebacks; reverse with pyobfus-unscrub (Pro, v0.5.1)",
)
@click.option(
    "--fingerprint",
    type=str,
    help="Per-buyer deterministic forensic watermark / L3 key (buyer id, Pro, v0.5.1)",
)
@click.option(
    "--expire-hard",
    type=str,
    help="Module-top crypto-bound expiry check, ISO date (Pro, v0.5.1; distinct from --expire)",
)
@click.option(
    "--period",
    type=int,
    default=0,
    help="Module-top run-counter limit; refuses import after N runs "
    "(Pro, v0.5.3; distinct from --max-runs)",
)
@click.option(
    "--opacity-config",
    type=click.Path(exists=True, dir_okay=False),
    help="opacity.toml with pattern->layer rules; encrypts matching functions "
    "by pre-mangle qualname (Pro, v0.5.3; implies --selective-opacity)",
)
@click.option(
    "--bind-device",
    is_flag=True,
    help="Bind L3 opacity and/or --vault keys to this build machine; decrypts "
    "only on it (Pro, v0.5.3; pairs with --selective-opacity/--opacity-config "
    "and/or --vault; distinct from --bind-machine)",
)
@click.option(
    "--bind-device-id",
    type=str,
    help="Bind L3 encryption to a supplied machine-id instead of the build "
    "machine (Pro, v0.5.3; implies --bind-device)",
)
@click.option(
    "--preset",
    type=click.Choice(
        [
            # Community
            "safe",
            "balanced",
            "aggressive",
            # Framework-aware (community-tier)
            "fastapi",
            "django",
            "flask",
            "pydantic",
            "click",
            "sqlalchemy",
            "ml",
            # Pro
            "trial",
            "commercial",
            "library",
            "maximum",
        ],
        case_sensitive=False,
    ),
    help="Use a preset configuration. Community: safe/balanced/aggressive. "
    "Framework-aware: fastapi/django/flask/pydantic/click/sqlalchemy/ml. "
    "Pro: trial/commercial/library/maximum.",
)
@click.option(
    "--list-presets",
    is_flag=True,
    help="List all available presets with descriptions",
)
@click.option(
    "--stats",
    is_flag=True,
    help="Show obfuscation statistics summary",
)
@click.option(
    "-j",
    "--jobs",
    type=int,
    default=0,
    help="Parallel workers (0=auto, 1=sequential, N=N workers)",
)
@click.option(
    "--check",
    "check_mode",
    is_flag=True,
    help="Pre-flight risk check: scan for eval/exec, dynamic attributes, "
    "framework reflection points. No files are written. "
    "Exit code 0=safe, 1=high-risk findings, 2=parse errors.",
)
@click.option(
    "--json",
    "json_output",
    is_flag=True,
    help="Emit machine-readable JSON output (for --check and future AI-agent integrations).",
)
@click.option(
    "--save-mapping",
    "save_mapping_path",
    type=click.Path(),
    help="Write original→obfuscated name mapping to a JSON file. "
    "Use with `pyobfus --unmap` to reverse obfuscated stack traces.",
)
@click.option(
    "--trace-marker/--no-trace-marker",
    "trace_marker",
    default=False,
    help="Prepend a '# pyobfus:obfuscated' header (id + mapping filename + the "
    "exact --unmap command) to each obfuscated file, so an AI agent that lands "
    "in an obfuscated file from a traceback knows to reverse the names. "
    "Requires --save-mapping. Default: off.",
)
@click.option(
    "--unmap",
    "unmap_mode",
    is_flag=True,
    help="Reverse obfuscated names back to originals. Reads stack trace from "
    "--trace FILE (or stdin) and applies --mapping FILE.",
)
@click.option(
    "--trace",
    "trace_path",
    type=click.Path(),
    help="Path to an obfuscated stack trace or error log (used with --unmap). "
    "Pass '-' to read from stdin.",
)
@click.option(
    "--mapping",
    "mapping_path",
    type=click.Path(),
    help="Path to a mapping.json file produced by --save-mapping (used with --unmap).",
)
@click.option(
    "--init",
    "init_mode",
    is_flag=True,
    help="Scan project, detect frameworks, and generate pyobfus.yaml with a "
    "suggested preset and exclude patterns. Zero-config onboarding for "
    "new projects (or AI agents wiring up pyobfus for the user).",
)
@click.option(
    "--incremental",
    is_flag=True,
    help="Skip the run when every input file and the config are unchanged "
    "since the last successful build (cache at <output>/.pyobfus-cache/). "
    "Useful in CI pipelines that cache build artifacts.",
)
@click.version_option(version=__version__, prog_name="pyobfus")
def main(
    input_path: Optional[str],
    output_path: Optional[str],
    config_path: Optional[str],
    init_config_template: Optional[str],
    validate_config_path: Optional[str],
    level: str,
    remove_docstrings: bool,
    remove_comments: bool,
    name_prefix: str,
    preserve_param_names: bool,
    numeric_obfuscation: bool,
    strip_ai_artifacts: bool,
    verbose: bool,
    dry_run: bool,
    cross_file: bool,
    upgrade: bool,
    control_flow: bool,
    string_encryption: bool,
    anti_debug: bool,
    dead_code: bool,
    expire: Optional[str],
    bind_machine: bool,
    max_runs: int,
    selective_opacity: bool,
    seal_code: bool,
    vault_flag: bool,
    scrub_traceback: bool,
    fingerprint: Optional[str],
    expire_hard: Optional[str],
    period: int,
    opacity_config: Optional[str],
    bind_device: bool,
    bind_device_id: Optional[str],
    preset: Optional[str],
    list_presets: bool,
    stats: bool,
    jobs: int,
    check_mode: bool,
    json_output: bool,
    save_mapping_path: Optional[str],
    trace_marker: bool,
    unmap_mode: bool,
    trace_path: Optional[str],
    mapping_path: Optional[str],
    init_mode: bool,
    incremental: bool,
) -> None:
    """
    Obfuscate Python source code.

    INPUT_PATH: Python file or directory to obfuscate

    \b
    Examples:
      pyobfus script.py -o script_obf.py
      pyobfus src/ -o dist/
      pyobfus src/ -o dist/ --config pyobfus.yaml
      pyobfus --check src/                  # pre-flight risk scan
      pyobfus --check src/ --json           # machine-readable report
      pyobfus --init-config django
      pyobfus --validate-config pyobfus.yaml
    """
    # Handle --check: pre-flight risk scan (no output files)
    if check_mode:
        if not input_path:
            click.echo("Error: --check requires INPUT_PATH.", err=True)
            sys.exit(1)
        _handle_check(Path(input_path), json_output=json_output)
        return

    # Handle --unmap: reverse obfuscated names in a stack trace
    if unmap_mode:
        _handle_unmap(
            trace_path=trace_path,
            mapping_path=mapping_path,
            json_output=json_output,
        )
        return

    # Handle --init: scan project and generate pyobfus.yaml
    if init_mode:
        scan_root = Path(input_path) if input_path else Path.cwd()
        _handle_init(scan_root, json_output=json_output)
        return

    # Handle --upgrade: Show Pro edition information
    if upgrade:
        _handle_upgrade()
        return

    # Handle --list-presets: Show available presets
    if list_presets:
        _handle_list_presets()
        return

    # Handle --init-config: Generate configuration template
    if init_config_template:
        _handle_init_config(init_config_template)
        return

    # Handle --validate-config: Validate configuration file
    if validate_config_path:
        _handle_validate_config(validate_config_path)
        return

    # For obfuscation, input_path and output_path are required
    if not input_path:
        click.echo("Error: Missing argument 'INPUT_PATH'.", err=True)
        click.echo("\nUsage: pyobfus INPUT_PATH -o OUTPUT_PATH", err=True)
        click.echo("\nOr use utility commands:", err=True)
        click.echo("  pyobfus --init-config django     Generate Django config template", err=True)
        click.echo("  pyobfus --validate-config FILE   Validate config file", err=True)
        sys.exit(1)

    if not output_path:
        if json_output:
            _emit_error_json(
                "UsageError",
                "Missing required option '-o' / '--output'.",
                "Pass -o PATH to specify output location.",
                "pyobfus INPUT -o OUTPUT [options]",
                exit_code=1,
            )
        else:
            click.echo("Error: Missing required option '-o' / '--output'.", err=True)
        sys.exit(1)

    # In JSON mode, buffer all chatty intermediate output so the final JSON
    # on stdout stays parseable. Text is discarded (stats go into the JSON).
    _saved_stdout = sys.stdout
    if json_output:
        sys.stdout = io.StringIO()

    try:
        # Load configuration
        effective_config_path = config_path

        # Auto-discover config if not specified
        if not config_path:
            auto_config = _try_auto_discover_config(verbose)
            if auto_config:
                effective_config_path = str(auto_config)

        if effective_config_path:
            config = ObfuscationConfig.from_file(Path(effective_config_path))
            if verbose:
                click.echo(f"Loaded configuration from: {effective_config_path}")
        elif preset:
            # Use preset configuration
            pro_presets = ["trial", "commercial", "library", "maximum"]
            if preset.lower() in pro_presets:
                # Check Pro access for Pro presets
                trial_active = is_trial_active()
                has_pro_access = trial_active or PRO_AVAILABLE

                if not has_pro_access:
                    click.echo(
                        f"Error: The '{preset}' preset requires Pro edition or active trial.",
                        err=True,
                    )
                    click.echo("\nStart a free 5-day trial:", err=True)
                    click.echo("  pyobfus-trial start", err=True)
                    click.echo(
                        f"\nOr purchase a license (${PRO_PRICE_USD} one-time):",
                        err=True,
                    )
                    click.echo(f"  {STRIPE_PAYMENT_LINK}", err=True)
                    sys.exit(1)

            config = ObfuscationConfig.get_preset(preset.lower())
            if verbose:
                click.echo(f"Using preset: {preset}")
        else:
            # Use default based on level
            if level == "pro":
                # Check trial status first (refreshed at runtime)
                trial_active = is_trial_active()

                if trial_active:
                    # Trial is active - allow Pro features without license
                    trial_msg = get_trial_expiry_message()
                    if verbose:
                        click.echo(f"Trial mode: {trial_msg}")
                    config = ObfuscationConfig.pro_edition()
                elif PRO_AVAILABLE:
                    # Pro edition installed - verify license
                    assert pyobfus_pro is not None, "pyobfus_pro module should be loaded"

                    try:
                        # Get cached license status (unmasked to get full key)
                        cached_status = pyobfus_pro.get_license_status(masked=False)
                        if not cached_status:
                            click.echo(
                                "Error: No license key found. Please register your license first.",
                                err=True,
                            )
                            click.echo(
                                "\nTo register your license key, run:",
                                err=True,
                            )
                            click.echo(
                                "  pyobfus-license register YOUR-LICENSE-KEY",
                                err=True,
                            )
                            click.echo(
                                "\nOr start a free 5-day trial:",
                                err=True,
                            )
                            click.echo(
                                "  pyobfus-trial start",
                                err=True,
                            )
                            click.echo(
                                "\nPurchase a license at: https://github.com/zhurong2020/pyobfus",
                                err=True,
                            )
                            sys.exit(1)

                        # Verify the cached license (use unmasked key)
                        full_license_key = cached_status["key"]
                        license_result = pyobfus_pro.verify_license(full_license_key)

                        if verbose:
                            click.echo(f"License verified: {license_result['message']}")

                    except pyobfus_pro.LicenseError as e:
                        click.echo(
                            f"Error: License verification failed - {e}",
                            err=True,
                        )
                        click.echo(
                            "\nPlease check your license status with: pyobfus-license status",
                            err=True,
                        )
                        click.echo(
                            "Or register a new license: pyobfus-license register YOUR-LICENSE-KEY",
                            err=True,
                        )
                        click.echo(
                            "\nOr start a free 5-day trial: pyobfus-trial start",
                            err=True,
                        )
                        sys.exit(1)

                    config = ObfuscationConfig.pro_edition()
                else:
                    # No Pro installed and no trial - show options
                    click.echo(
                        "Error: Pro edition features require a license or active trial.",
                        err=True,
                    )
                    click.echo(
                        "\nStart a free 5-day trial (no registration required):",
                        err=True,
                    )
                    click.echo(
                        "  pyobfus-trial start",
                        err=True,
                    )
                    click.echo(
                        "\nOr purchase a license ($45 one-time):",
                        err=True,
                    )
                    click.echo(
                        f"  {STRIPE_PAYMENT_LINK}",
                        err=True,
                    )
                    sys.exit(1)
            else:
                config = ObfuscationConfig.community_edition()

        # Override config with CLI options
        config.level = level
        config.remove_docstrings = remove_docstrings
        config.remove_comments = remove_comments
        config.name_prefix = name_prefix
        config.preserve_param_names = preserve_param_names
        if numeric_obfuscation:
            config.numeric_obfuscation = True
        if strip_ai_artifacts:
            config.strip_ai_artifacts = True
        config.max_workers = jobs if jobs > 0 else None  # 0=auto, N=explicit

        # Handle Pro feature flags
        license_embedding_requested = expire or bind_machine or max_runs > 0
        fusion_requested = (
            selective_opacity
            or seal_code
            or vault_flag
            or scrub_traceback
            or fingerprint
            or expire_hard
            or period > 0
            or opacity_config
            or bind_device
            or bind_device_id
        )
        pro_features_requested = (
            control_flow
            or string_encryption
            or anti_debug
            or dead_code
            or license_embedding_requested
            or fusion_requested
        )
        if pro_features_requested:
            # Check if user has Pro access (license or trial)
            trial_active = is_trial_active()
            has_pro_access = trial_active or PRO_AVAILABLE

            if not has_pro_access:
                click.echo(
                    "Error: Pro features require a license or active trial.",
                    err=True,
                )
                click.echo(
                    "\nStart a free 5-day trial (no registration required):",
                    err=True,
                )
                click.echo("  pyobfus-trial start", err=True)
                click.echo(
                    f"\nOr purchase a license (${PRO_PRICE_USD} one-time):",
                    err=True,
                )
                click.echo(f"  {STRIPE_PAYMENT_LINK}", err=True)
                sys.exit(1)

            # User has Pro access - enable requested features
            config.level = "pro"
            if control_flow:
                config.control_flow_flattening = True
                if verbose:
                    click.echo("Enabled: Control Flow Flattening")
            if string_encryption:
                config.string_encryption = True
                if verbose:
                    click.echo("Enabled: AES-256 String Encryption")
            if anti_debug:
                config.anti_debug = True
                if verbose:
                    click.echo("Enabled: Anti-Debugging Protection")
            if dead_code:
                config.dead_code_injection = True
                if verbose:
                    click.echo("Enabled: Dead Code Injection")

            # License embedding options
            if expire:
                config.license_expire = expire
                if verbose:
                    click.echo(f"Enabled: License Expiration ({expire})")
            if bind_machine:
                config.license_bind_machine = True
                if verbose:
                    click.echo("Enabled: Machine Binding")
            if max_runs > 0:
                config.license_max_runs = max_runs
                if verbose:
                    click.echo(f"Enabled: Run Limit ({max_runs} runs)")

            # v0.5.1 patent-targeted Pro mechanisms (build-fusion)
            if selective_opacity:
                config.selective_opacity = True
                if verbose:
                    click.echo("Enabled: Selective Opacity (P2-1)")
            if seal_code:
                config.seal_code = True
                if verbose:
                    click.echo("Enabled: @seal_code integrity (P2-9)")
            if vault_flag:
                config.vault = True
                if verbose:
                    click.echo("Enabled: Runtime String Vault (P2-11)")
            if scrub_traceback:
                config.scrub_traceback = True
                if verbose:
                    click.echo("Enabled: Traceback scrubbing (P2-10)")
            if fingerprint:
                config.fingerprint = fingerprint
                if verbose:
                    click.echo("Enabled: Forensic watermark (P2-7)")
            if expire_hard:
                config.expire_hard = expire_hard
                if verbose:
                    click.echo(f"Enabled: Hard expiry check ({expire_hard})")
            if period > 0:
                config.period_max_runs = period
                if verbose:
                    click.echo(f"Enabled: Run-counter limit ({period} runs, P2-8)")
            if opacity_config:
                config.opacity_config = opacity_config
                config.selective_opacity = True
                if verbose:
                    click.echo(f"Enabled: Opacity config rules ({opacity_config}, P2-1)")
            if bind_device or bind_device_id:
                config.bind_device = True
                if bind_device_id:
                    config.bind_device_id = bind_device_id
                if verbose:
                    _target = f"device {bind_device_id}" if bind_device_id else "build machine"
                    click.echo(f"Enabled: Device binding ({_target}, P2-8)")

            if fusion_requested and cross_file and Path(input_path).is_dir():
                click.echo(
                    "Note: v0.5.1 Pro mechanisms run per-file and (like existing "
                    "Pro features) are not applied in cross-file directory mode. "
                    "Use --no-cross-file or a single file.",
                    err=True,
                )

        # Determine if input is file or directory
        input_path_obj = Path(input_path)
        output_path_obj = Path(output_path)

        if dry_run:
            click.echo("\n[DRY RUN MODE] - No files will be written")

        # Initialize statistics
        obfuscation_stats: dict = {
            "files_processed": 0,
            "files_skipped": 0,
            "total_names_obfuscated": 0,
            "strings_encoded": 0,
            "strings_encrypted": 0,
            "control_flow_applied": 0,
            "dead_code_injected": 0,
            "anti_debug_checks": 0,
        }

        # Incremental short-circuit: directory mode only (single-file
        # rebuilds are cheap enough to skip this machinery)
        if incremental and input_path_obj.is_dir() and not dry_run:
            from pyobfus.core.cache import BuildCache

            cache = BuildCache(output_path_obj)
            input_files_for_sig = filter_python_files(input_path_obj, config.exclude_patterns)
            current_sig = cache.build_signature(input_path_obj, input_files_for_sig, config)
            hit, reason, cached_outputs = cache.can_reuse(current_sig)
            if hit:
                click.echo(
                    f"\nIncremental: skipping — {reason} "
                    f"({len(cached_outputs or [])} output file(s) reused)"
                )
                obfuscation_stats["files_processed"] = 0
                obfuscation_stats["files_skipped"] = len(cached_outputs or [])
                # Short-circuit to summary
                if json_output:
                    sys.stdout = _saved_stdout
                    _emit_obfuscate_success_json(
                        input_path=input_path,
                        output_path=output_path,
                        preset=preset,
                        level=config.level,
                        dry_run=dry_run,
                        stats=obfuscation_stats,
                        mapping_path=save_mapping_path,
                    )
                    return
                # Fall through to normal text success path below by
                # flagging that we have nothing more to do
                click.echo("\nObfuscation completed successfully! (cache hit)")
                return
            elif verbose:
                click.echo(f"\nIncremental: rebuilding — {reason}")

        if input_path_obj.is_file():
            # Single file obfuscation
            file_stats = _obfuscate_file(
                input_path_obj,
                output_path_obj,
                config,
                verbose,
                dry_run,
                save_mapping_path=save_mapping_path,
            )
            if file_stats:
                obfuscation_stats["files_processed"] = 1
                for key, value in file_stats.items():
                    if key in obfuscation_stats:
                        obfuscation_stats[key] += value
        elif input_path_obj.is_dir():
            # Directory obfuscation - use CrossFileOrchestrator if enabled
            if cross_file:
                dir_stats = _obfuscate_directory_crossfile(
                    input_path_obj,
                    output_path_obj,
                    config,
                    verbose,
                    dry_run,
                    save_mapping_path=save_mapping_path,
                )
                if dir_stats:
                    obfuscation_stats.update(dir_stats)
            else:
                # Legacy single-file mode
                dir_stats = _obfuscate_directory(
                    input_path_obj, output_path_obj, config, verbose, dry_run
                )
                if dir_stats:
                    obfuscation_stats.update(dir_stats)

            # Save manifest after a successful rebuild (directory mode only)
            if incremental and not dry_run and input_path_obj.is_dir():
                from pyobfus.core.cache import BuildCache

                cache = BuildCache(output_path_obj)
                final_inputs = filter_python_files(input_path_obj, config.exclude_patterns)
                output_files = []
                for f in final_inputs:
                    try:
                        rel = f.relative_to(input_path_obj)
                    except ValueError:
                        continue
                    output_files.append(str(output_path_obj / rel))
                final_sig = cache.build_signature(input_path_obj, final_inputs, config)
                cache.save_manifest(final_sig, output_files)
        else:
            click.echo(f"Error: {input_path} is neither a file nor a directory", err=True)
            sys.exit(1)

        # Auto-unmap convention: stamp each obfuscated file with a stable
        # '# pyobfus:obfuscated' header pointing at the mapping + unmap command,
        # so an AI agent that opens an obfuscated file from a traceback knows to
        # reverse the names. Opt-in (--trace-marker) and requires a mapping.
        trace_marker_id: Optional[str] = None
        if trace_marker and not dry_run:
            if save_mapping_path:
                trace_marker_id = _apply_trace_markers(output_path_obj, save_mapping_path)
                if verbose:
                    click.echo(f"  Stamped trace marker (id={trace_marker_id})")
            else:
                click.echo(
                    "Warning: --trace-marker has no effect without --save-mapping "
                    "(the marker points at a mapping file). Skipped.",
                    err=True,
                )

        if json_output:
            sys.stdout = _saved_stdout
            _emit_obfuscate_success_json(
                input_path=input_path,
                output_path=output_path,
                preset=preset,
                level=config.level,
                dry_run=dry_run,
                stats=obfuscation_stats,
                mapping_path=save_mapping_path,
                trace_marker_id=trace_marker_id,
            )
            return

        if not dry_run:
            click.echo("\nObfuscation completed successfully!")
        else:
            click.echo("\n[DRY RUN] Preview completed. Use without --dry-run to write files.")

        # Display statistics if requested
        if stats and not dry_run:
            _display_stats(obfuscation_stats, config)

        # Subtle Pro feature hint (only for Community users without trial)
        if level == "community" and not PRO_AVAILABLE and not is_trial_active():
            click.echo("\nTip: Try Pro FREE for 5 days - AES-256 encryption & anti-debugging")
            click.echo("     Start trial: pyobfus-trial start")

    except LimitExceededError as e:
        sys.stdout = _saved_stdout
        if json_output:
            _emit_error_json(
                "LimitExceededError",
                str(e),
                "Community Edition is capped at 5 files / 1000 LOC. "
                "Start a free 5-day trial: pyobfus-trial start",
                "pyobfus-trial start",
                exit_code=1,
            )
        else:
            click.echo(f"\nError: {e}", err=True)
            click.echo("\nConsider upgrading to pyobfus Pro for unlimited obfuscation.")
        sys.exit(1)
    except PyObfusError as e:
        sys.stdout = _saved_stdout
        if json_output:
            _emit_error_json(
                type(e).__name__,
                str(e),
                "Run 'pyobfus --check INPUT' to scan for incompatible constructs.",
                f"pyobfus --check {input_path}",
                exit_code=1,
            )
        else:
            click.echo(f"\nError: {e}", err=True)
        sys.exit(1)
    except Exception as e:
        sys.stdout = _saved_stdout
        if json_output:
            _emit_error_json(
                type(e).__name__,
                str(e),
                "Unexpected error — re-run with --verbose for a traceback, "
                "and open an issue at https://github.com/zhurong2020/pyobfus/issues.",
                "pyobfus --verbose",
                exit_code=1,
            )
        else:
            click.echo(f"\nUnexpected error: {e}", err=True)
            if verbose:
                import traceback

                traceback.print_exc()
        sys.exit(1)
    finally:
        # Restore stdout in case we returned via an unhandled path
        if sys.stdout is not _saved_stdout:
            sys.stdout = _saved_stdout


def _obfuscate_file(
    input_file: Path,
    output_file: Path,
    config: ObfuscationConfig,
    verbose: bool,
    dry_run: bool = False,
    save_mapping_path: Optional[str] = None,
) -> dict:
    """
    Obfuscate a single Python file.

    Args:
        input_file: Input Python file
        output_file: Output file path
        config: Obfuscation configuration
        verbose: Verbose output
        dry_run: Preview mode without writing files

    Returns:
        Dictionary with obfuscation statistics
    """
    file_stats: dict = {
        "total_names_obfuscated": 0,
        "strings_encoded": 0,
        "numbers_obfuscated": 0,
        "ai_docstrings_stripped": 0,
        "ai_attributions_stripped": 0,
        "strings_encrypted": 0,
        "control_flow_applied": 0,
        "dead_code_injected": 0,
        "anti_debug_checks": 0,
    }
    if verbose:
        click.echo(f"\nObfuscating: {input_file}")

    # Parse file. v0.5.1 Pro fusion: the vault PRE-pass must run on the source
    # before Core touches it, so vault_secrets({...}) literals are encrypted to
    # bytes before the string-encoder would otherwise mangle them.
    _fusion = (
        config.level == "pro" and _build_fusion is not None and _build_fusion.fusion_enabled(config)
    )
    if _fusion:
        source_text = input_file.read_text(encoding="utf-8")
        source_text = _build_fusion.apply_pre_passes(
            source_text, config, module_qualname=input_file.stem
        )
        tree = ASTParser.parse_string(source_text, filename=str(input_file))
    else:
        tree = ASTParser.parse_file(input_file)

    # Count lines for Community Edition limits
    line_count = ASTParser.count_lines(tree)
    if config.max_total_loc and line_count > config.max_total_loc:
        raise LimitExceededError("lines_of_code", line_count, config.max_total_loc)

    # Analyze symbols
    analyzer = SymbolAnalyzer(config)
    analyzer.analyze(tree)

    if verbose:
        stats = analyzer.get_statistics()
        click.echo(f"  Total names: {stats['total_names']}")
        click.echo(f"  Obfuscatable names: {stats['obfuscatable_names']}")
        click.echo(f"  Excluded names: {stats['excluded_names']}")

    # Transform - Apply transformations in sequence
    transformed_tree = tree

    # 0. Strip AI provenance markers (Community - if enabled). Runs first so it
    # sees original docstrings and dunder names before mangling rewrites them.
    if config.strip_ai_artifacts:
        from pyobfus.transformers.ai_artifact_stripper import AIArtifactStripper

        ai_stripper = AIArtifactStripper(config, analyzer)
        transformed_tree = ai_stripper.transform(transformed_tree)
        ai_stats = ai_stripper.get_statistics()
        file_stats["ai_docstrings_stripped"] = ai_stats.get("docstrings_stripped", 0)
        file_stats["ai_attributions_stripped"] = ai_stats.get("attributions_stripped", 0)

        if verbose:
            click.echo(
                f"  AI artifacts stripped: "
                f"{ai_stats['docstrings_stripped']} docstring(s), "
                f"{ai_stats['attributions_stripped']} attribution(s)"
            )

    # 1. Name mangling (always applied)
    mangler = NameMangler(config, analyzer)
    transformed_tree = mangler.transform(transformed_tree)
    file_stats["total_names_obfuscated"] = mangler.get_transformation_count()

    if verbose:
        click.echo(f"  Name transformations: {mangler.get_transformation_count()}")

    # Save single-file mapping if requested
    if save_mapping_path and not dry_run:
        from pyobfus.core.mapping import ObfuscationMapping

        mapping = ObfuscationMapping.from_single_file(
            mangler.get_name_mapping(),
            root=str(input_file.parent),
            module=input_file.stem,
        )
        mapping.save(save_mapping_path)
        if verbose:
            click.echo(f"  Wrote mapping: {save_mapping_path}")

    # 2. String encoding (Community Edition - if enabled)
    if config.string_encoding and config.level == "community":
        from pyobfus.transformers.string_encoder import StringEncoder

        string_encoder = StringEncoder(config, analyzer)
        transformed_tree = string_encoder.transform(transformed_tree)
        encoder_stats = string_encoder.get_statistics()
        file_stats["strings_encoded"] = encoder_stats.get("encoded_strings", 0)

        if verbose:
            click.echo(f"  Encoded strings: {encoder_stats['encoded_strings']}")
            if encoder_stats["skipped_fstrings"] > 0:
                click.echo(f"  Skipped f-strings: {encoder_stats['skipped_fstrings']}")

    # 2.5 Numeric / constant obfuscation (Community Edition - if enabled)
    # Runs after string encoding so the float.fromhex() hex strings it emits
    # are not themselves re-encoded; runs after name mangling so the injected
    # `float` builtin reference is never renamed.
    if config.numeric_obfuscation:
        from pyobfus.transformers.numeric_obfuscator import NumericObfuscator

        numeric_obfuscator = NumericObfuscator(config, analyzer)
        transformed_tree = numeric_obfuscator.transform(transformed_tree)
        numeric_stats = numeric_obfuscator.get_statistics()
        file_stats["numbers_obfuscated"] = numeric_stats.get("numbers_obfuscated", 0)

        if verbose:
            click.echo(f"  Numbers obfuscated: {numeric_stats['numbers_obfuscated']}")

    # 3. Pro features (if enabled)
    if config.level == "pro":
        try:
            # Control Flow Flattening
            if config.control_flow_flattening:
                from pyobfus_pro.control_flow import ControlFlowFlattener

                cff = ControlFlowFlattener()
                transformed_tree = cff.visit(transformed_tree)
                file_stats["control_flow_applied"] = 1

                if verbose:
                    click.echo("  Control flow flattening: Applied")

            # String encryption (AES-256)
            if config.string_encryption:
                from pyobfus_pro.string_aes import StringAESEncryptor

                string_encryptor = StringAESEncryptor(config, analyzer)
                transformed_tree = string_encryptor.transform(transformed_tree)
                encryptor_stats = string_encryptor.get_statistics()
                file_stats["strings_encrypted"] = encryptor_stats.get("encrypted_strings", 0)

                if verbose:
                    click.echo(f"  Encrypted strings: {encryptor_stats['encrypted_strings']}")

            # Anti-debugging checks
            if config.anti_debug:
                from pyobfus_pro.anti_debug import AntiDebugInjector

                anti_debug = AntiDebugInjector(config, analyzer)
                transformed_tree = anti_debug.transform(transformed_tree)
                anti_debug_stats = anti_debug.get_statistics()
                file_stats["anti_debug_checks"] = anti_debug_stats.get("injected_functions", 0) + 1

                if verbose:
                    click.echo(f"  Anti-debug checks: {anti_debug_stats['injected_functions'] + 1}")

            # Dead Code Injection
            if config.dead_code_injection:
                from pyobfus_pro.dead_code import DeadCodeInjector

                dead_code_injector = DeadCodeInjector()
                transformed_tree = dead_code_injector.visit(transformed_tree)
                dci_stats = dead_code_injector.get_statistics()
                file_stats["dead_code_injected"] = dci_stats.get("injected_statements", 0)

                if verbose:
                    click.echo(
                        f"  Dead code injection: {dci_stats['injected_statements']} statements"
                    )

            # License Embedding (applied last to inject at module start)
            license_embed_enabled = (
                config.license_expire or config.license_bind_machine or config.license_max_runs > 0
            )
            if license_embed_enabled:
                from pyobfus_pro.license_embed import LicenseEmbedder, LicenseEmbedConfig

                embed_config = LicenseEmbedConfig(
                    expire_date=config.license_expire,
                    bind_machine=config.license_bind_machine,
                    max_runs=config.license_max_runs,
                )
                license_embedder = LicenseEmbedder(embed_config)
                transformed_tree = license_embedder.visit(transformed_tree)

                if verbose:
                    embed_info = []
                    if config.license_expire:
                        embed_info.append(f"expires {config.license_expire}")
                    if config.license_bind_machine:
                        fp = license_embedder.get_current_fingerprint()
                        embed_info.append(f"bound to {fp[:8]}...")
                    if config.license_max_runs > 0:
                        embed_info.append(f"max {config.license_max_runs} runs")
                    click.echo(f"  License embedding: {', '.join(embed_info)}")

        except ImportError as e:
            click.echo(f"\n⚠️  Pro features not available: {e}", err=True)
            click.echo("Please ensure pyobfus Pro is properly installed.", err=True)
            if verbose:
                click.echo("Pro features require additional modules in pyobfus_pro/", err=True)
            # Continue with Community Edition features only

    # Generate code
    obfuscated_code = CodeGenerator.generate(transformed_tree)

    # v0.5.1 Pro fusion POST-passes: opacity (encrypt final mangled bytecode),
    # seal (hash final bytecode / ciphertext for L3), scrub (excepthook), and
    # the hard-expiry check. These run on the generated source, so they capture
    # the fully-obfuscated output and their emitted infra is never re-mangled.
    if _fusion:
        scrub_key_path = output_file.with_suffix(output_file.suffix + ".scrub.key.pem")
        obfuscated_code = _build_fusion.apply_post_passes(
            obfuscated_code,
            config,
            module_qualname=input_file.stem,
            scrub_key_path=scrub_key_path,
        )
        if verbose:
            enc, _ = _build_fusion.assignments_summary(obfuscated_code)
            if config.selective_opacity:
                click.echo(f"  Selective Opacity: {enc} function(s) L3-encrypted")
            if config.scrub_traceback:
                click.echo(f"  Scrub keypair: {scrub_key_path} (keep private)")

    # Add header comment
    obfuscated_code = CodeGenerator.add_header_comment(obfuscated_code, str(input_file))

    # Write output
    if not dry_run:
        if _fusion:
            # The fusion post-passes transformed the source string, so write it
            # directly rather than regenerating from the (pre-fusion) tree.
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text(obfuscated_code, encoding="utf-8")
        else:
            CodeGenerator.generate_to_file(transformed_tree, output_file)
        if verbose:
            click.echo(f"  Output: {output_file}")
    else:
        if verbose:
            click.echo(f"  Would write to: {output_file}")
            click.echo("  Preview (first 10 lines):")
            lines = obfuscated_code.split("\n")[:10]
            for line in lines:
                click.echo(f"    {line}")

    return file_stats


def _obfuscate_directory(
    input_dir: Path,
    output_dir: Path,
    config: ObfuscationConfig,
    verbose: bool,
    dry_run: bool = False,
) -> dict:
    """
    Obfuscate all Python files in a directory (legacy single-file mode).

    Args:
        input_dir: Input directory
        output_dir: Output directory
        config: Obfuscation configuration
        verbose: Verbose output
        dry_run: Preview mode without writing files

    Returns:
        Dictionary with aggregated obfuscation statistics
    """
    dir_stats: dict = {
        "files_processed": 0,
        "total_names_obfuscated": 0,
        "strings_encoded": 0,
        "strings_encrypted": 0,
        "control_flow_applied": 0,
        "dead_code_injected": 0,
        "anti_debug_checks": 0,
    }

    # Find all Python files, excluding patterns from config
    python_files = filter_python_files(input_dir, config.exclude_patterns)

    if not python_files:
        click.echo(f"No Python files found in {input_dir}")
        return dir_stats

    if verbose and config.exclude_patterns:
        click.echo(f"Excluding patterns: {', '.join(config.exclude_patterns)}")

    # Check Community Edition file limit
    if config.max_files and len(python_files) > config.max_files:
        raise LimitExceededError("file_count", len(python_files), config.max_files)

    click.echo(f"\nFound {len(python_files)} Python file(s) to obfuscate")

    # Check total LOC limit
    if config.max_total_loc:
        total_loc = 0
        for file in python_files:
            try:
                tree = ASTParser.parse_file(file)
                total_loc += ASTParser.count_lines(tree)
            except Exception:
                pass  # Count what we can

        if total_loc > config.max_total_loc:
            raise LimitExceededError("total_lines_of_code", total_loc, config.max_total_loc)

    # Obfuscate each file
    total = len(python_files)
    for idx, python_file in enumerate(python_files, 1):
        rel_path = python_file.relative_to(input_dir)
        output_file = output_dir / rel_path

        if not verbose and total > 1:
            pct = idx * 100 // total
            click.echo(f"\r  Processing: {idx}/{total} ({pct}%)", nl=False)

        try:
            file_stats = _obfuscate_file(python_file, output_file, config, verbose, dry_run)
            dir_stats["files_processed"] += 1
            for key, value in file_stats.items():
                if key in dir_stats:
                    dir_stats[key] += value
        except PyObfusError as e:
            click.echo(f"  Warning: Failed to obfuscate {python_file}: {e}", err=True)

    if not verbose and total > 1:
        click.echo()  # newline after progress

    return dir_stats


def _obfuscate_directory_crossfile(
    input_dir: Path,
    output_dir: Path,
    config: ObfuscationConfig,
    verbose: bool,
    dry_run: bool = False,
    save_mapping_path: Optional[str] = None,
) -> dict:
    """
    Obfuscate directory with cross-file import mapping using CrossFileOrchestrator.

    Args:
        input_dir: Input directory
        output_dir: Output directory
        config: Obfuscation configuration
        verbose: Verbose output
        dry_run: Preview mode without writing files

    Returns:
        Dictionary with obfuscation statistics
    """
    dir_stats: dict = {
        "files_processed": 0,
        "total_names_obfuscated": 0,
        "strings_encoded": 0,
        "strings_encrypted": 0,
        "control_flow_applied": 0,
        "dead_code_injected": 0,
        "anti_debug_checks": 0,
    }

    if verbose:
        click.echo("\nUsing cross-file obfuscation mode")
        click.echo(f"Input:  {input_dir}")
        click.echo(f"Output: {output_dir}")

    # Create orchestrator
    orchestrator = CrossFileOrchestrator(config)

    try:
        # Phase 1: Scan
        if verbose:
            click.echo("\n[Phase 1] Scanning project...")

        global_table = orchestrator.phase1_scan(input_dir)

        stats = orchestrator.get_statistics()
        dir_stats["files_processed"] = stats.get("files_discovered", 0)
        dir_stats["total_names_obfuscated"] = stats.get("total_exports", 0)

        click.echo(f"\nDiscovered {stats['files_discovered']} Python file(s)")
        click.echo(f"  Modules: {stats['total_modules']}")
        click.echo(f"  Exports: {stats['total_exports']}")

        # Validate
        is_valid, errors = global_table.validate()
        if not is_valid:
            click.echo("\nWarning: Some imports cannot be resolved:", err=True)
            for error in errors[:5]:  # Show first 5 errors
                click.echo(f"  - {error}", err=True)
            if len(errors) > 5:
                click.echo(f"  ... and {len(errors) - 5} more", err=True)
            click.echo("\nThese may be standard library or external imports (OK to continue)")

        if dry_run:
            click.echo("\n[DRY RUN] Would transform files with these mappings:")
            for module in sorted(global_table.get_all_modules())[:5]:
                exports = global_table.get_module_exports(module)
                if exports:
                    click.echo(f"\n  Module: {module}")
                    for orig, obf in list(exports.items())[:3]:
                        click.echo(f"    {orig} -> {obf}")
            if stats["total_modules"] > 5:
                click.echo(f"\n  ... and {stats['total_modules'] - 5} more modules")
            return dir_stats

        # Phase 2: Transform
        if verbose:
            workers_desc = f"{config.max_workers} workers" if config.max_workers else "auto"
            click.echo(f"\n[Phase 2] Transforming files... (parallel: {workers_desc})")

        completed = [0]
        total = stats["files_discovered"]

        def _progress(module_name: str, error: Optional[str]) -> None:
            completed[0] += 1
            if verbose:
                status = "OK" if not error else f"FAILED: {error}"
                click.echo(f"  [{completed[0]}/{total}] {module_name} ... {status}")
            elif not error:
                # Simple progress line
                pct = completed[0] * 100 // total
                click.echo(
                    f"\r  Processing: {completed[0]}/{total} ({pct}%)",
                    nl=False,
                )

        transform_errors = orchestrator.phase2_transform(
            input_dir,
            output_dir,
            progress_callback=_progress,
        )

        if not verbose and total > 0:
            click.echo()  # newline after progress

        if transform_errors:
            click.echo(f"\nWarnings: {len(transform_errors)} file(s) had errors:", err=True)
            for err in transform_errors[:5]:
                click.echo(f"  - {err}", err=True)

        click.echo(f"\nSuccessfully obfuscated {stats['files_discovered']} file(s)")

        if verbose:
            click.echo(f"\nOutput written to: {output_dir}")

        # Save cross-file mapping if requested
        if save_mapping_path:
            from pyobfus.core.mapping import ObfuscationMapping

            mapping = ObfuscationMapping.from_global_table(
                orchestrator.global_table, root=str(input_dir)
            )
            mapping.save(save_mapping_path)
            click.echo(f"Wrote mapping: {save_mapping_path} ({mapping.stats()})")

        return dir_stats

    except Exception as e:
        click.echo(f"\nError during cross-file obfuscation: {e}", err=True)
        if verbose:
            import traceback

            traceback.print_exc()
        sys.exit(1)


def _handle_upgrade() -> None:
    """
    Display Pro edition features and purchase information.
    """
    # Check current status
    trial_active = is_trial_active()
    trial_msg = get_trial_expiry_message()

    if PRO_AVAILABLE:
        click.echo("\n" + "=" * 60)
        click.echo("  pyobfus Professional Edition - ACTIVE")
        click.echo("=" * 60)
        click.echo("\nYour Pro license is active. You have access to all features:")
        click.echo("  - AES-256 string encryption (--string-encryption)")
        click.echo("  - Anti-debugging protection (--anti-debug)")
        click.echo("  - Unlimited files and lines of code")
        click.echo("  - Priority email support")
        click.echo("\nRun 'pyobfus-license status' to view license details.")
        return

    if trial_active:
        click.echo("\n" + "=" * 60)
        click.echo("  pyobfus Professional Edition - TRIAL ACTIVE")
        click.echo("=" * 60)
        click.echo(f"\n  {trial_msg}")
        click.echo("\n  You have access to all Pro features:")
        click.echo("  - AES-256 string encryption (--level pro)")
        click.echo("  - Anti-debugging protection (--level pro)")
        click.echo("  - Unlimited files and lines of code")
        click.echo("")
        click.echo("  To keep using Pro after trial:")
        click.echo(f"  ${PRO_PRICE_USD}.00 USD (one-time payment)")
        click.echo(f"  {STRIPE_PAYMENT_LINK}")
        click.echo("")
        click.echo("  Check trial status: pyobfus-trial status")
        click.echo("=" * 60)
        return

    # Show Pro edition information for Community users
    click.echo("\n" + "=" * 60)
    click.echo("  pyobfus Professional Edition")
    click.echo("=" * 60)
    click.echo("")
    click.echo("  TRY FREE FOR 5 DAYS")
    click.echo("  --------------------")
    click.echo("  No registration or credit card required!")
    click.echo("  Start now: pyobfus-trial start")
    click.echo("")
    click.echo("  FEATURES")
    click.echo("  ---------")
    click.echo("  [x] AES-256 string encryption")
    click.echo("      Encrypt all strings with military-grade encryption")
    click.echo("")
    click.echo("  [x] Anti-debugging protection")
    click.echo("      Detect and prevent debugger attachment")
    click.echo("")
    click.echo("  [x] Unlimited files & lines of code")
    click.echo("      No restrictions on project size")
    click.echo("")
    click.echo("  [x] Priority email support")
    click.echo("      Get help within 24 hours")
    click.echo("")
    click.echo("  PRICING")
    click.echo("  --------")
    click.echo("  $45.00 USD (one-time payment)")
    click.echo("  - 50% cheaper than PyArmor Pro ($89)")
    click.echo("  - Lifetime license, no subscription")
    click.echo("  - 30-day money-back guarantee")
    click.echo("")
    click.echo("  PURCHASE")
    click.echo("  ---------")
    click.echo(f"  {STRIPE_PAYMENT_LINK}")
    click.echo("")
    click.echo("  After purchase, activate with:")
    click.echo("    pip install --upgrade pyobfus")
    click.echo("    pyobfus-license register YOUR-LICENSE-KEY")
    click.echo("")
    click.echo("=" * 60)


def _handle_list_presets() -> None:
    """
    Display all available presets with descriptions.
    """
    click.echo("\n" + "=" * 60)
    click.echo("  pyobfus Configuration Presets")
    click.echo("=" * 60)

    click.echo("\n  COMMUNITY PRESETS (Free)")
    click.echo("  " + "-" * 30)

    click.echo("\n  safe")
    click.echo("    Preserves docstrings and public APIs")
    click.echo("    Ideal for libraries and production code")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset safe")

    click.echo("\n  balanced (default)")
    click.echo("    Removes docstrings, obfuscates private names")
    click.echo("    Good balance between security and compatibility")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset balanced")

    click.echo("\n  aggressive")
    click.echo("    Obfuscates everything possible")
    click.echo("    Use with caution - may break code")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset aggressive")

    click.echo("\n  FRAMEWORK-AWARE PRESETS (Free — built on 'safe')")
    click.echo("  " + "-" * 30)

    click.echo("\n  fastapi")
    click.echo("    Preserves dependency-injection param names + HTTP verbs")
    click.echo("    Auto-excludes **/routers/**, **/dependencies.py")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset fastapi")

    click.echo("\n  django")
    click.echo("    Preserves ORM, CBV, signals, forms, admin")
    click.echo("    Auto-excludes migrations/, urls.py, settings.py, manage.py")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset django")

    click.echo("\n  flask")
    click.echo("    Preserves view functions and url_for() targets")
    click.echo("    Auto-excludes **/views/**, **/blueprints/**")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset flask")

    click.echo("\n  pydantic")
    click.echo("    Preserves BaseModel field API (v1 and v2)")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset pydantic")

    click.echo("\n  click")
    click.echo("    Preserves CLI command/group/option parameter names")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset click")

    click.echo("\n  sqlalchemy")
    click.echo("    Preserves ORM columns, relationships, session API")
    click.echo("    Auto-excludes alembic/, migrations/")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset sqlalchemy")

    click.echo("\n  ml")
    click.echo("    Preserves model-serving wrapper APIs and model artifact paths")
    click.echo("    Auto-excludes models/, checkpoints/, common weight files")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset ml")

    click.echo("\n  PRO PRESETS (Requires Pro license or trial)")
    click.echo("  " + "-" * 30)

    click.echo("\n  trial")
    click.echo("    30-day time-limited version")
    click.echo("    All Pro features + expiration date")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset trial")

    click.echo("\n  commercial")
    click.echo("    Maximum protection for paid software")
    click.echo("    CFF + DCI + AES + Anti-debug + Machine binding")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset commercial")

    click.echo("\n  library")
    click.echo("    For distributing Python libraries")
    click.echo("    Preserves APIs, encrypts internal code")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset library")

    click.echo("\n  maximum")
    click.echo("    Highest security for sensitive code")
    click.echo("    All features + machine binding + run limits")
    click.echo("    Usage: pyobfus src/ -o dist/ --preset maximum")

    click.echo("\n" + "=" * 60)
    click.echo("\n  Start a free 5-day trial: pyobfus-trial start")
    click.echo("")


def _handle_init_config(template_name: str) -> None:
    """
    Generate configuration template file.

    Args:
        template_name: Template type (django, flask, library, general)
    """
    output_file = Path("pyobfus.yaml")

    # Check if file already exists
    if output_file.exists():
        if not click.confirm(f"'{output_file}' already exists. Overwrite?"):
            click.echo("Aborted.")
            return

    try:
        template_content = get_template(template_name)
        output_file.write_text(template_content, encoding="utf-8")
        click.echo(f"Generated '{output_file}' with {template_name} template")
        click.echo("\nNext steps:")
        click.echo("  1. Review and customize the configuration")
        click.echo(f"  2. Run: pyobfus src/ -o dist/ -c {output_file}")
    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        click.echo(f"\nAvailable templates: {', '.join(list_templates())}", err=True)
        sys.exit(1)


def _emit_success_json_payload(payload: Dict[str, Any]) -> None:
    """Serialize a success payload to stdout (one JSON object)."""
    click.echo(json.dumps(payload, indent=2, ensure_ascii=False))


# PEP 263 encoding cookie — must stay within the first two lines of a file, so
# the trace marker is inserted *after* it (and after any shebang) to avoid
# silently disabling the declared source encoding.
_CODING_COOKIE_RE = re.compile(r"coding[:=]\s*([-\w.]+)")


def _trace_marker_block(marker_id: str, mapping_basename: str) -> str:
    """Build the '# pyobfus:obfuscated' header block (trailing newline included)."""
    return (
        f"{TRACE_MARKER_PREFIX} id={marker_id} mapping={mapping_basename}\n"
        f"# Obfuscated with pyobfus ({GITHUB_REPO}). The original names are recoverable.\n"
        f"# To de-obfuscate a traceback from this file:\n"
        f"#   pyobfus --unmap --trace <logfile> --mapping {mapping_basename}\n"
    )


def _insert_after_prologue(text: str, marker_block: str) -> str:
    """Prepend `marker_block`, but keep a shebang line first and a PEP 263
    encoding cookie within the first two lines."""
    lines = text.splitlines(keepends=True)
    idx = 0
    if idx < len(lines) and lines[idx].startswith("#!"):
        idx += 1
    if idx < len(lines) and idx < 2 and _CODING_COOKIE_RE.search(lines[idx]):
        idx += 1
    return "".join(lines[:idx]) + marker_block + "".join(lines[idx:])


def _apply_trace_markers(output_path: Path, mapping_path: str) -> Optional[str]:
    """Stamp every obfuscated `.py` file under `output_path` with the trace marker.

    Returns the mapping's `marker_id` (read from the saved mapping JSON), or
    None if the mapping can't be read. Idempotent: files that already carry the
    marker are left untouched, so re-running is safe.
    """
    mp = Path(mapping_path)
    try:
        marker_id = json.loads(mp.read_text(encoding="utf-8")).get("marker_id")
    except (OSError, ValueError):
        return None
    if not isinstance(marker_id, str) or not marker_id:
        return None

    block = _trace_marker_block(marker_id, mp.name)
    targets: List[Path] = (
        [output_path] if output_path.is_file() else sorted(output_path.rglob("*.py"))
    )
    for f in targets:
        try:
            txt = f.read_text(encoding="utf-8")
        except OSError:
            continue
        if TRACE_MARKER_PREFIX in txt[:512]:
            continue  # already stamped — keep idempotent
        f.write_text(_insert_after_prologue(txt, block), encoding="utf-8")
    return marker_id


def _emit_obfuscate_success_json(
    input_path: str,
    output_path: str,
    preset: Optional[str],
    level: str,
    dry_run: bool,
    stats: Dict[str, int],
    mapping_path: Optional[str],
    trace_marker_id: Optional[str] = None,
) -> None:
    """Emit the obfuscation success summary as JSON."""
    # AI hint: suggest the most useful next command based on context
    if mapping_path:
        ai_hint = (
            f"Obfuscation complete. To reverse a production traceback: "
            f"pyobfus --unmap --trace error.log --mapping {mapping_path}"
        )
    elif dry_run:
        ai_hint = "Dry run complete — no files written. Remove --dry-run to persist output."
    else:
        ai_hint = (
            "Obfuscation complete. Add '--save-mapping mapping.json' next time "
            "to enable 'pyobfus --unmap' for debugging obfuscated stack traces."
        )

    payload: Dict[str, Any] = {
        "version": 1,
        "status": "success",
        "input": input_path,
        "output": output_path,
        "preset": preset,
        "level": level,
        "dry_run": dry_run,
        "stats": stats,
        "mapping": mapping_path,
        "trace_marker_id": trace_marker_id,
        "ai_hint": ai_hint,
    }
    _emit_success_json_payload(payload)


def _emit_error_json(
    error_type: str,
    message: str,
    suggestion: str,
    ai_hint: str,
    exit_code: int = 1,
) -> None:
    """Emit a structured error payload as JSON."""
    payload = {
        "version": 1,
        "status": "error",
        "error_type": error_type,
        "message": message,
        "suggestion": suggestion,
        "ai_hint": ai_hint,
        "exit_code": exit_code,
    }
    click.echo(json.dumps(payload, indent=2, ensure_ascii=False))


def _handle_init(scan_root: Path, json_output: bool = False) -> None:
    """
    Scan a project and write a suggested `pyobfus.yaml`.

    When `--json` is set, emits a structured payload on stdout and exits
    without asking for confirmation (overwrites existing file). The JSON
    mode is intended for AI agents and CI pipelines.
    """
    from pyobfus.core.init_config import build_init_result

    result = build_init_result(scan_root)
    target = result.config_path

    if target.exists() and not json_output:
        if not click.confirm(f"'{target}' already exists. Overwrite?"):
            click.echo("Aborted.")
            return

    target.write_text(result.yaml_text, encoding="utf-8")
    result.written = True

    if json_output:
        payload = result.to_dict()
        payload["status"] = "success"
        # Context-aware next-step for AI agents
        if result.high_risk_findings > 0:
            payload["ai_hint"] = (
                f"Generated {target}. "
                f"{result.high_risk_findings} high-risk pattern(s) detected — "
                f"run 'pyobfus --check {scan_root}' for details before obfuscating."
            )
        else:
            payload["ai_hint"] = (
                f"Generated {target}. Next: pyobfus {scan_root} -o dist/ -c {target}"
            )
        click.echo(json.dumps(payload, indent=2, ensure_ascii=False))
        return

    click.echo(f"Generated {target}")
    click.echo(f"  Preset: {result.preset}")
    if result.frameworks_detected:
        click.echo(f"  Frameworks detected: {', '.join(result.frameworks_detected)}")
    click.echo(f"  Files scanned: {result.files_scanned}")
    click.echo(f"  Exclude patterns: {len(result.excludes)} entries")
    if result.high_risk_findings > 0:
        click.echo(
            f"  Warning: {result.high_risk_findings} high-risk pattern(s) detected. "
            f"Run 'pyobfus --check {scan_root}' for details."
        )
    click.echo("")
    click.echo("Next steps:")
    click.echo(f"  1. Review {target}")
    click.echo(f"  2. Run: pyobfus {scan_root} -o dist/ -c {target}")


def _handle_unmap(
    trace_path: Optional[str],
    mapping_path: Optional[str],
    json_output: bool = False,
) -> None:
    """
    Reverse obfuscated identifiers in a stack trace / error log.

    Reads text from `trace_path` (or stdin when `-`) and substitutes every
    known obfuscated identifier with its original name, using a mapping.json
    produced by --save-mapping. Prints the rewritten text to stdout.
    """
    from pyobfus.core.mapping import ObfuscationMapping

    if not mapping_path:
        click.echo("Error: --unmap requires --mapping PATH.", err=True)
        click.echo("Example: pyobfus --unmap --trace error.log --mapping mapping.json", err=True)
        sys.exit(2)

    try:
        mapping = ObfuscationMapping.load(Path(mapping_path))
    except FileNotFoundError as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(2)
    except (ValueError, json.JSONDecodeError) as e:  # noqa: F821 — json imported below
        click.echo(f"Error: invalid mapping file: {e}", err=True)
        sys.exit(2)

    if trace_path in (None, "-"):
        trace_text = sys.stdin.read()
    else:
        trace_file = Path(trace_path)  # type: ignore[arg-type]
        if not trace_file.exists():
            click.echo(f"Error: trace file not found: {trace_path}", err=True)
            sys.exit(2)
        trace_text = trace_file.read_text(encoding="utf-8")

    if not trace_text.strip():
        click.echo("Error: no trace input (empty file or stdin).", err=True)
        sys.exit(2)

    rewritten = mapping.unmap_text(trace_text)

    if json_output:
        click.echo(
            json.dumps(
                {
                    "version": 1,
                    "mapping": str(mapping_path),
                    "mapping_stats": mapping.stats(),
                    "original_trace": trace_text,
                    "unmapped_trace": rewritten,
                    "ai_hint": (
                        "Unmapped names use the pre-obfuscation identifiers; "
                        "line numbers still refer to the obfuscated output."
                    ),
                },
                indent=2,
                ensure_ascii=False,
            )
        )
    else:
        click.echo(rewritten, nl=False)


def _handle_check(input_path: Path, json_output: bool = False) -> None:
    """
    Run pre-flight risk scan and print report.

    Exits with code 0 (safe), 1 (high-severity findings), or 2 (parse errors).
    """
    from pyobfus.core.preflight import PreflightChecker, format_report_text

    checker = PreflightChecker()
    report = checker.check_path(input_path)

    if json_output:
        click.echo(report.to_json())
    else:
        click.echo(format_report_text(report))

    sys.exit(report.exit_code())


def _handle_validate_config(config_path: str) -> None:
    """
    Validate a configuration file and report errors/warnings.

    Args:
        config_path: Path to configuration file
    """
    click.echo(f"Validating: {config_path}\n")

    result = validate_config_file(Path(config_path))

    # Print errors
    for error in result.errors:
        click.echo(error, err=True)

    # Print warnings
    for warning in result.warnings:
        click.echo(warning)

    # Print suggestions
    for suggestion in result.suggestions:
        click.echo(suggestion)

    # Print summary
    click.echo(f"\n{result.get_summary()}")

    if not result.is_valid:
        sys.exit(1)


def _try_auto_discover_config(verbose: bool) -> Optional[Path]:
    """
    Try to auto-discover configuration file.

    Args:
        verbose: Whether to print discovery messages

    Returns:
        Path to config file if found, None otherwise
    """
    config_path, _ = find_config_file()

    if config_path:
        if verbose:
            click.echo(f"Auto-discovered config: {config_path}")
        return config_path

    return None


def _display_stats(stats: dict, config: ObfuscationConfig) -> None:
    """
    Display obfuscation statistics summary.

    Args:
        stats: Dictionary with obfuscation statistics
        config: Obfuscation configuration
    """
    click.echo("\n" + "=" * 50)
    click.echo("  Obfuscation Statistics")
    click.echo("=" * 50)

    click.echo(f"\n  Files processed:      {stats.get('files_processed', 0)}")
    click.echo(f"  Names obfuscated:     {stats.get('total_names_obfuscated', 0)}")

    if stats.get("strings_encoded", 0) > 0:
        click.echo(f"  Strings encoded:      {stats['strings_encoded']}")

    if config.level == "pro":
        if stats.get("strings_encrypted", 0) > 0:
            click.echo(f"  Strings encrypted:    {stats['strings_encrypted']}")
        if stats.get("control_flow_applied", 0) > 0:
            click.echo(f"  Control flow files:   {stats['control_flow_applied']}")
        if stats.get("dead_code_injected", 0) > 0:
            click.echo(f"  Dead code statements: {stats['dead_code_injected']}")
        if stats.get("anti_debug_checks", 0) > 0:
            click.echo(f"  Anti-debug checks:    {stats['anti_debug_checks']}")

    click.echo("\n" + "=" * 50)


if __name__ == "__main__":
    main()
