"""
Single source of truth for pyobfus.yaml's configuration schema.

Derived from ObfuscationConfig's actual dataclass fields
(dataclasses.fields()) so the set of recognized keys can never silently
drift out of sync with the config it describes. Found 2026-08-06:
config_validator.py's old hand-maintained VALID_SCHEMA dict had drifted
stale -- missing `preset` (the key `pyobfus --init` itself writes into
every config it generates) and every Pro field added since v0.5.0 --
producing false "Unknown configuration key" warnings on --init's own
output. See docs/VSCODE_EXTENSION_PLAN.md's M3 section for the full
investigation.

Two consumers:
- pyobfus.config_validator (CLI `--validate-config`) calls describe_fields()
  live, every call -- there's no cached/generated artifact for this
  consumer to go stale.
- scripts/generate_vscode_schema.py (release-time, not a runtime
  dependency of this package) walks the same data to emit a standard JSON
  Schema file for the VS Code extension's `pyobfus.yaml` IntelliSense.
"""

from dataclasses import MISSING, fields
from typing import Any, Dict, List, Union, get_args, get_origin

from pyobfus.config import ObfuscationConfig

# Best-effort human-readable enrichment, keyed by field name.
#
# Deliberately NOT the source of truth for which fields exist, their
# types, or their defaults -- that always comes straight from
# dataclasses.fields(ObfuscationConfig) in describe_fields() below. A
# field missing from this dict still gets a full, correctly-typed schema
# entry with a generic description, never a silently-omitted one: that
# silent omission was exactly the failure mode this module exists to
# close, so this dict is allowed to fall behind without reintroducing it.
_FIELD_DESCRIPTIONS: Dict[str, str] = {
    "level": "Obfuscation level.",
    "exclude_patterns": "File patterns to exclude (glob syntax). Extends the "
    "preset's baseline, doesn't replace it.",
    "exclude_names": "Names to never rename (builtins, imports, Pro "
    "infrastructure, ...). Extends the preset's baseline.",
    "name_prefix": "Prefix for obfuscated identifier names.",
    "remove_docstrings": "Strip docstrings from the output.",
    "remove_comments": "Strip comments from the output.",
    "string_encoding": "Simple Base64 string encoding (Community).",
    "numeric_obfuscation": "Opaque arithmetic identities for numeric " "literals (Community).",
    "strip_ai_artifacts": 'Remove AI provenance markers ("Generated by '
    'Claude", etc.) from docstrings and attribution dunders (Community).',
    "preserve_param_names": "Keep function parameter names intact so "
    "keyword arguments survive obfuscation.",
    "string_encryption": "AES-256 string encryption (Pro).",
    "import_obfuscation": "Rewrite imports to runtime importlib calls + "
    "encrypted import strings (Pro).",
    "anti_debug": "Inject runtime debugger-detection checks: sys.gettrace, "
    "TracerPid, IsDebuggerPresent, timing skew (Pro).",
    "control_flow_flattening": "Flatten control flow into an opaque " "dispatch loop (Pro).",
    "dead_code_injection": "Inject plausible-looking dead code as decoy " "(Pro).",
    "license_expire": "License expiration date (YYYY-MM-DD). Import raises "
    "after this date (Pro).",
    "license_bind_machine": "Bind the license to the current machine's "
    "hardware fingerprint (Pro).",
    "license_max_runs": "Maximum run count before the license refuses to "
    "run; 0 = unlimited (Pro).",
    "selective_opacity": "Enable per-symbol layered protection (opacity "
    "layers) for @opacity-decorated functions (Pro).",
    "seal_code": "Bytecode integrity seal for @seal_code-decorated "
    "functions -- detects in-memory patching (Pro).",
    "vault": "Encrypt vault_secrets({...}) runtime constants into an " "AES-256-GCM Vault (Pro).",
    "scrub_traceback": "Encrypt production tracebacks (RSA-2048-OAEP + "
    "AES-256-GCM hybrid); reverse with pyobfus-unscrub (Pro).",
    "fingerprint": "Per-buyer deterministic forensic watermark key (buyer " "id) (Pro).",
    "expire_hard": "Module-top hard expiration check (ISO date) baked " "into the build (Pro).",
    "period_max_runs": "Module-top run-counter limit baked into the " "build (Pro).",
    "opacity_config": "Path to an opacity.toml pattern-driven " "layer-assignment file (Pro).",
    "bind_device": "Derive Selective Opacity + Vault keys from the bound "
    "machine's fingerprint at runtime (Pro).",
    "bind_device_id": "Target machine-id for bind_device; omit to use "
    "the build machine's own fingerprint (Pro).",
    "requires_os": "Comma-separated allowed OS names (platform.system() "
    "values) -- import refuses to run elsewhere (Pro).",
    "requires_python_min": 'Minimum required Python version, e.g. "3.10" ' "(Pro).",
    "requires_arch": "Comma-separated allowed CPU architectures "
    "(platform.machine() values) (Pro).",
    "embed_data": "Path to a resource file to AES-256-GCM encrypt and "
    "embed as a module constant (Pro).",
    "max_workers": "Parallel worker count for multi-file builds; omit "
    "for the automatic cpu_count-based default.",
    "max_files": "Optional self-imposed cap on files per build; omit for "
    "unlimited (the default -- pyobfus does not limit project size at "
    "any tier). Only enforced for a single-file build or a directory "
    "build run with --no-cross-file; the default cross-file directory "
    "build does not check it.",
    "max_total_loc": "Optional self-imposed cap on total lines of code per "
    "build; omit for unlimited (the default). Enforced for a single-file "
    "build or --no-cross-file directory build; not checked in the default "
    "cross-file directory build.",
}

# Fields that require `level: pro` (or a preset that sets it). Kept
# separate from _FIELD_DESCRIPTIONS rather than folded into it so a field
# can pick up a correct pro_only flag even before anyone gets around to
# writing its prose description.
_PRO_ONLY_FIELDS = {
    "string_encryption",
    "import_obfuscation",
    "anti_debug",
    "control_flow_flattening",
    "dead_code_injection",
    "license_expire",
    "license_bind_machine",
    "license_max_runs",
    "selective_opacity",
    "seal_code",
    "vault",
    "scrub_traceback",
    "fingerprint",
    "expire_hard",
    "period_max_runs",
    "opacity_config",
    "bind_device",
    "bind_device_id",
    "requires_os",
    "requires_python_min",
    "requires_arch",
    "embed_data",
}

_LEVEL_VALUES = ["community", "pro"]

# Numeric lower bounds not derivable from the type annotation alone.
_MIN_VALUES: Dict[str, int] = {
    "max_files": 1,
    "max_total_loc": 1,
}


def _resolve_field_default(default: Any, default_factory: Any) -> Any:
    if default is not MISSING:
        return default
    if default_factory is not MISSING:
        return default_factory()
    return None


def _json_type_for(python_type: Any) -> Dict[str, Any]:
    """
    Map a dataclass field's type annotation to a (json_type, item_type)
    pair. Handles the concrete shapes ObfuscationConfig actually uses:
    str, bool, int, List[str], Set[str], Optional[str], Optional[int].
    Anything unrecognized degrades to a generic "string" rather than
    raising -- a new field with an unmapped type still gets a schema
    entry (fixing the actual bug this module exists for), just a less
    precise one, instead of silently vanishing again.
    """
    origin = get_origin(python_type)

    if python_type is bool:
        return {"json_type": "boolean"}
    if python_type is str:
        return {"json_type": "string"}
    if python_type is int:
        return {"json_type": "integer"}

    if origin is list or origin is set:
        (item_type,) = get_args(python_type) or (str,)
        return {"json_type": "array", "item_type": _json_type_for(item_type)["json_type"]}

    if origin is Union:
        args = [a for a in get_args(python_type) if a is not type(None)]
        if len(args) == 1:
            inner = _json_type_for(args[0])
            inner["nullable"] = True
            return inner

    # Fallback: unrecognized annotation shape.
    return {"json_type": "string"}


def describe_fields() -> List[Dict[str, Any]]:
    """
    Introspect ObfuscationConfig's actual dataclass fields and return
    structured metadata for each: name, json_type, item_type (for arrays),
    nullable, default (JSON-safe), description, pro_only, valid_values
    (only set for `level`).

    This is the single source of truth for "what keys does pyobfus.yaml's
    `obfuscation:` section accept" -- every consumer should derive from
    this rather than hand-maintaining its own copy.
    """
    described: List[Dict[str, Any]] = []
    for f in fields(ObfuscationConfig):
        default = _resolve_field_default(f.default, f.default_factory)
        if isinstance(default, set):
            default = sorted(default)

        entry: Dict[str, Any] = {
            "name": f.name,
            "default": default,
            "description": _FIELD_DESCRIPTIONS.get(
                f.name, f"{f.name} (see pyobfus.config.ObfuscationConfig)."
            ),
            "pro_only": f.name in _PRO_ONLY_FIELDS,
        }
        entry.update(_json_type_for(f.type))
        if f.name == "level":
            entry["valid_values"] = _LEVEL_VALUES
        if f.name in _MIN_VALUES:
            entry["min_value"] = _MIN_VALUES[f.name]
        described.append(entry)
    return described


def preset_names() -> List[str]:
    """Available top-level `preset:` values, from ObfuscationConfig.list_presets()."""
    return ObfuscationConfig.list_presets()
