"""
Centralized constants for pyobfus.

This file contains all URLs and configuration that may need to change.
Update values here instead of searching through multiple files.

Single Source of Truth Pattern:
- All Python files import from here
- Documentation files reference these values (update manually when changed)
"""

# =============================================================================
# PAYMENT & PURCHASE
# =============================================================================

# Stripe Payment Link (Live Mode)
# To update: Change this value, then update docs manually (see DOCS_TO_UPDATE below)
STRIPE_PAYMENT_LINK = "https://buy.stripe.com/00w4gr8ta9F78Fj8oI9k400"

# Price
PRO_PRICE_USD = 45

# =============================================================================
# SUPPORT & CONTACT
# =============================================================================

SUPPORT_EMAIL = "zhurong0525@gmail.com"
GITHUB_REPO = "https://github.com/zhurong2020/pyobfus"

# =============================================================================
# TRACE MARKER (auto-unmap convention)
# =============================================================================
# A stable header prepended to obfuscated files (opt-in via --trace-marker) so
# an AI agent that lands in an obfuscated file from a traceback immediately
# knows the artifact is pyobfus-obfuscated and how to reverse the names.
# The first token is matched verbatim by tooling — do not reword.
TRACE_MARKER_PREFIX = "# pyobfus:obfuscated"

# =============================================================================
# BUILD MARKER (transparent attribution)
# =============================================================================
# A short comment block identifying a file as pyobfus output. Distinct from
# TRACE_MARKER_PREFIX on purpose: tooling must be able to tell "this file was
# generated by pyobfus" apart from "a mapping exists to reverse it". The first
# token is matched verbatim -- do not reword.
#
# This marker is attribution, NOT a license check, authenticity proof or
# anti-piracy measure. See docs/COMMUNITY_BUILD_MARKER_DESIGN.md.
BUILD_MARKER_PREFIX = "# pyobfus:generated"
BUILD_MARKER_FORMAT = 1

# =============================================================================
# LICENSE SERVER
# =============================================================================
# Note: This URL is also defined in pyobfus_pro/license.py (for package independence)
# Keep both in sync if the URL changes!

LICENSE_API_URL = "https://pyobfus-license-server.zhurong0525.workers.dev/api/verify"

# Server-registered trial issuance (opt-in via `pyobfus-trial start --email`).
# Same Worker as LICENSE_API_URL. Keep the host in sync with pyobfus_pro/license.py.
TRIAL_API_URL = "https://pyobfus-license-server.zhurong0525.workers.dev/api/trial/request"

# =============================================================================
# DOCUMENTATION FILES TO UPDATE MANUALLY
# =============================================================================
# When changing STRIPE_PAYMENT_LINK, also update these files:
#
# DOCS_TO_UPDATE = [
#     "README.md (line ~96)",
#     "docs/index.md (lines ~43, ~141)",
#     "CHANGELOG.md (line ~204)",
#     "vscode-extension/src/commands/proFunnel.ts (STRIPE_PAYMENT_LINK/PRICE_USD/"
#     "MONEY_BACK_DAYS/TRIAL_DAYS constants -- TS can't import this module directly)",
# ]
# =============================================================================

# =============================================================================
# REDISTRIBUTABLE PRO RUNTIME
# =============================================================================
# Artifacts produced by the Pro fusion passes import ``pyobfus_runtime``, a
# separately published, redistributable package. pyproject.toml declares the
# exact requirement below so a build machine always has it (the pyobfus_pro
# package shipped in this wheel re-exports it and cannot import without it);
# a target machine installs only the runtime beside the artifact.
# Keep these values and the pyproject.toml dependency line in sync --
# tests/test_runtime_requirement.py asserts it.
RUNTIME_DISTRIBUTION = "pyobfus-runtime"
RUNTIME_IMPORT_NAME = "pyobfus_runtime"
RUNTIME_REQUIREMENT_SPECIFIER = ">=0.1,<1"
RUNTIME_REQUIREMENT = RUNTIME_DISTRIBUTION + RUNTIME_REQUIREMENT_SPECIFIER
