"""Runtime accessor for ``--embed-data`` (P2-14): AES-256-GCM encrypted resource files.

Closes the Nuitka Commercial "Protect Data Files" / PyArmor ``--bind-data``
gap: at build time, the orchestrator reads a resource file's raw bytes,
encrypts them with AES-256-GCM (same construction as the Runtime String
Vault -- 12-byte random nonce, 32-byte key, GCM authentication tag), and
emits the result base85-encoded as a module-level string constant plus a
generated ``get_embedded_data()`` accessor that reverses the process at
call time. Decryption is on-demand, not at import.

Not part of the patent-gated P2-1/7/8/9/10/11 combination claims -- reuses
the same AES-256-GCM primitive as the Runtime String Vault (P2-11) but for
an arbitrary binary blob rather than a named string KV store.
"""

from __future__ import annotations

import base64
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

_NONCE_SIZE = 12  # AES-GCM standard
_KEY_SIZE = 32  # 256-bit AES key


class EmbeddedDataError(RuntimeError):
    """Raised when embedded-data encryption/decryption fails.

    Covers a wrong-size key, malformed base85, or a tampered/wrong-key
    ciphertext (GCM tag mismatch).
    """


def encrypt_data_file(data: bytes, key: bytes) -> bytes:
    """Encrypt raw bytes with AES-256-GCM. Returns ``nonce || ciphertext_with_tag``.

    Called by the build orchestrator (``--embed-data``) at build time; not
    typically called directly by end users of an obfuscated artifact.

    Args:
        data: The raw file bytes to encrypt.
        key: A 32-byte AES key (fresh random per build, generated by the
            orchestrator via ``secrets.token_bytes(32)``).

    Raises:
        EmbeddedDataError: if ``key`` is not exactly 32 bytes.
    """
    if len(key) != _KEY_SIZE:
        raise EmbeddedDataError(f"key must be {_KEY_SIZE} bytes; got {len(key)}")
    nonce = os.urandom(_NONCE_SIZE)
    aesgcm = AESGCM(key)
    ciphertext = aesgcm.encrypt(nonce, data, associated_data=None)
    return bytes(nonce + ciphertext)


def get_embedded_data(blob_b85: str, key: bytes) -> bytes:
    """Decode + decrypt a base85-encoded AES-256-GCM blob emitted by ``--embed-data``.

    This is the function the build orchestrator's generated
    ``get_embedded_data()`` module-level wrapper calls at runtime.

    Args:
        blob_b85: base85-encoded ``nonce || ciphertext_with_tag``, as
            produced by :func:`encrypt_data_file` then
            ``base64.b85encode(...).decode("ascii")``.
        key: The same 32-byte AES key used to encrypt.

    Returns:
        The original file bytes.

    Raises:
        EmbeddedDataError: on a wrong-size key, malformed base85, a blob
            too short to contain a valid nonce, or a GCM tag mismatch
            (wrong key or tampered ciphertext).
    """
    if len(key) != _KEY_SIZE:
        raise EmbeddedDataError(f"key must be {_KEY_SIZE} bytes; got {len(key)}")
    try:
        blob = base64.b85decode(blob_b85)
    except ValueError as exc:
        raise EmbeddedDataError(f"blob is not valid base85: {exc}") from exc
    if len(blob) < _NONCE_SIZE:
        raise EmbeddedDataError("blob is too short to contain a valid nonce")
    nonce, ciphertext = blob[:_NONCE_SIZE], blob[_NONCE_SIZE:]
    aesgcm = AESGCM(key)
    try:
        return bytes(aesgcm.decrypt(nonce, ciphertext, associated_data=None))
    except InvalidTag as exc:
        raise EmbeddedDataError(
            "unable to decrypt embedded data (wrong key or tampered blob)"
        ) from exc


__all__ = ["EmbeddedDataError", "encrypt_data_file", "get_embedded_data"]
