"""
AI Artifact Stripper (Community Edition)

Removes AI-generation *provenance markers* that survive obfuscation, so code
authored with an AI assistant does not ship with "this was AI-generated"
fingerprints embedded in it.

Scope (deliberately conservative — near-zero false positives):
- **Docstrings** (module / function / class) whose text contains an AI
  attribution marker are removed entirely.
- **Attribution dunder assignments** (``__author__``, ``__copyright__``,
  ``__credits__``, ``__maintainer__``) whose string value contains an AI
  attribution marker are removed.

Explicitly NOT touched:
- Arbitrary string literals used as program data (a ``print("generated by
  claude")`` in business logic is left alone — only docstrings and attribution
  dunders are eligible).
- Regular comments — those are already dropped by the AST round-trip, so they
  never reach the output in the first place.

Only unambiguous provenance markers match (``Generated by Claude``,
``Co-Authored-By: Claude``, ``🤖 Generated with``, ...). Conversational
AI-tell phrasing is intentionally out of scope to avoid scrubbing legitimate
documentation.
"""

import ast
import re
from typing import Dict, List, Optional, cast

from pyobfus.config import ObfuscationConfig
from pyobfus.core.analyzer import SymbolAnalyzer
from pyobfus.core.transformer import BaseTransformer

# Unambiguous AI provenance / attribution markers (case-insensitive substring).
_AI_ATTRIBUTION_PATTERNS = [
    r"generated\s+(?:by|with)\s+(?:claude|copilot|chat\s*gpt|gpt|cursor|"
    r"codeium|tabnine|gemini|bard|openai|anthropic|ai)\b",
    r"co-?authored[-\s]?by\s*:?\s*(?:claude|copilot|chat\s*gpt|gpt|cursor|"
    r"gemini|openai|anthropic|ai)\b",
    r"\U0001f916\s*generated\s+with",  # 🤖 Generated with
    r"written\s+by\s+(?:claude|copilot|chat\s*gpt|gpt|cursor|gemini|ai)\b",
    r"(?:made|created)\s+(?:by|with)\s+(?:claude|copilot|chat\s*gpt|gpt|" r"cursor|gemini)\b",
    r"\bclaude\s+code\b",
]

_AI_MARKER_RE = re.compile("|".join(_AI_ATTRIBUTION_PATTERNS), re.IGNORECASE)

# Attribution dunders eligible for removal when their value is an AI marker.
_ATTRIBUTION_DUNDERS = frozenset(
    {"__author__", "__authors__", "__copyright__", "__credits__", "__maintainer__"}
)


def _is_ai_marker(text: str) -> bool:
    """Return True if the text contains any AI attribution marker."""
    return bool(_AI_MARKER_RE.search(text))


class AIArtifactStripper(BaseTransformer):
    """
    Strips AI provenance markers from docstrings and attribution dunders.

    Runs before name mangling so it sees original docstrings and dunder
    names. Bodies emptied by removal are backfilled with ``pass`` to keep
    function/class definitions valid.
    """

    def __init__(self, config: ObfuscationConfig, analyzer: Optional[SymbolAnalyzer] = None):
        super().__init__(config, analyzer)
        self._docstrings_stripped = 0
        self._attributions_stripped = 0

    def transform(self, tree: ast.Module) -> ast.Module:
        """
        Transform AST by removing AI provenance markers.

        Args:
            tree: Input AST

        Returns:
            ast.Module: Transformed AST
        """
        if not self.config.strip_ai_artifacts:
            return tree

        transformed = cast(ast.Module, self.visit(tree))
        ast.fix_missing_locations(transformed)
        return transformed

    # -- body-scoped nodes: filter their statement lists ------------------- #

    def visit_Module(self, node: ast.Module) -> ast.Module:
        self.generic_visit(node)
        node.body = self._filter_body(node.body, allow_empty=True)
        return node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        self.generic_visit(node)
        node.body = self._filter_body(node.body, allow_empty=False)
        return node

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> ast.AsyncFunctionDef:
        self.generic_visit(node)
        node.body = self._filter_body(node.body, allow_empty=False)
        return node

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        self.generic_visit(node)
        node.body = self._filter_body(node.body, allow_empty=False)
        return node

    # -- helpers ---------------------------------------------------------- #

    def _filter_body(self, body: List[ast.stmt], allow_empty: bool) -> List[ast.stmt]:
        """
        Return a new body with AI-attributed docstrings and dunders removed.

        Args:
            body: Original list of statements
            allow_empty: If False, append ``pass`` when the body becomes empty
                (functions/classes require a non-empty body)

        Returns:
            list[ast.stmt]: Filtered body
        """
        new_body: List[ast.stmt] = []
        for index, stmt in enumerate(body):
            # A docstring is a string Expr in the first position.
            if index == 0 and self._is_ai_docstring(stmt):
                self._docstrings_stripped += 1
                self._increment_transform_count()
                continue
            if self._is_ai_attribution_assign(stmt):
                self._attributions_stripped += 1
                self._increment_transform_count()
                continue
            new_body.append(stmt)

        if not new_body and not allow_empty:
            new_body.append(ast.Pass())

        return new_body

    @staticmethod
    def _is_ai_docstring(stmt: ast.stmt) -> bool:
        """True if stmt is a docstring whose text contains an AI marker."""
        return (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
            and _is_ai_marker(stmt.value.value)
        )

    @staticmethod
    def _is_ai_attribution_assign(stmt: ast.stmt) -> bool:
        """True if stmt assigns an attribution dunder to an AI-marker string."""
        # __author__ = "..."   (possibly chained targets)
        if isinstance(stmt, ast.Assign):
            value = stmt.value
            if not (isinstance(value, ast.Constant) and isinstance(value.value, str)):
                return False
            if not _is_ai_marker(value.value):
                return False
            return any(
                isinstance(t, ast.Name) and t.id in _ATTRIBUTION_DUNDERS for t in stmt.targets
            )
        # __author__: str = "..."
        if isinstance(stmt, ast.AnnAssign):
            value = stmt.value
            if value is None:
                return False
            if not (isinstance(value, ast.Constant) and isinstance(value.value, str)):
                return False
            if not _is_ai_marker(value.value):
                return False
            return isinstance(stmt.target, ast.Name) and stmt.target.id in _ATTRIBUTION_DUNDERS
        return False

    def get_statistics(self) -> Dict[str, int]:
        """
        Get stripping statistics.

        Returns:
            dict: Statistics about removed artifacts
        """
        return {
            "docstrings_stripped": self._docstrings_stripped,
            "attributions_stripped": self._attributions_stripped,
            "transformations": self._transformation_count,
        }
