"""
Project bootstrap: scan a directory and render a ready-to-use pyobfus.yaml.

Used by `pyobfus --init`. Delegates framework detection to the pre-flight
checker (`pyobfus/core/preflight.py`) so the suggestions stay in sync with
`pyobfus --check`, then emits a YAML config with a suggested preset,
auto-assembled `exclude_patterns`, and helpful inline comments that explain
*why* each line is there — both for humans and for AI coding assistants
reading the file to decide what to change.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from pyobfus import __version__ as PYOBFUS_VERSION
from pyobfus.core.preflight import PreflightChecker, PreflightReport


# Always-useful default excludes (test directories, venv, common cache)
_BASELINE_EXCLUDES: List[str] = [
    "test_*.py",
    "**/tests/**",
    "**/__pycache__/**",
    "**/.venv/**",
    "**/venv/**",
    "**/build/**",
    "**/dist/**",
]


@dataclass
class InitResult:
    """Outcome of `pyobfus --init`. Returned to the caller and rendered to YAML."""

    config_path: Path
    yaml_text: str
    preset: str
    excludes: List[str]
    frameworks_detected: List[str] = field(default_factory=list)
    files_scanned: int = 0
    high_risk_findings: int = 0
    written: bool = False  # True if the file was actually written to disk

    def to_dict(self) -> dict:
        return {
            "version": 1,
            "config_path": str(self.config_path),
            "preset": self.preset,
            "excludes": list(self.excludes),
            "frameworks_detected": list(self.frameworks_detected),
            "files_scanned": self.files_scanned,
            "high_risk_findings": self.high_risk_findings,
            "written": self.written,
        }


def build_init_result(
    scan_root: Path,
    config_path: Optional[Path] = None,
    preset_override: Optional[str] = None,
) -> InitResult:
    """Scan `scan_root`, detect frameworks, and compose the YAML text."""
    if config_path is None:
        config_path = scan_root / "pyobfus.yaml"

    report = PreflightChecker().check_path(scan_root)

    preset = preset_override or report.suggested_preset or "balanced"
    framework_names = sorted({fw.name for fw in report.frameworks})

    # Merge: framework-driven suggestions + baseline
    excludes: List[str] = []
    for pattern in list(report.suggested_excludes) + _BASELINE_EXCLUDES:
        if pattern and pattern not in excludes:
            excludes.append(pattern)

    yaml_text = _render_yaml(
        preset=preset,
        excludes=excludes,
        frameworks=framework_names,
        files_scanned=report.files_scanned,
        report=report,
        scan_root=scan_root,
    )

    return InitResult(
        config_path=config_path,
        yaml_text=yaml_text,
        preset=preset,
        excludes=excludes,
        frameworks_detected=framework_names,
        files_scanned=report.files_scanned,
        high_risk_findings=report.severity_counts().get("high", 0),
    )


def _render_yaml(
    preset: str,
    excludes: List[str],
    frameworks: List[str],
    files_scanned: int,
    report: PreflightReport,
    scan_root: Path,
) -> str:
    """Render the pyobfus.yaml content as a string with explanatory comments."""
    lines: List[str] = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Header with provenance
    lines.append(f"# pyobfus.yaml — generated by `pyobfus --init` on {now}")
    lines.append(f"# pyobfus v{PYOBFUS_VERSION}")
    lines.append(f"# Scanned: {scan_root}  ({files_scanned} Python file(s))")
    if frameworks:
        lines.append(f"# Detected frameworks: {', '.join(frameworks)}")
    else:
        lines.append("# No known frameworks detected.")
    hi = report.severity_counts().get("high", 0)
    md = report.severity_counts().get("medium", 0)
    if hi or md:
        lines.append(f"# Risks: {hi} high, {md} medium — run `pyobfus --check` for details.")
    lines.append("#")
    lines.append("# Edit this file to customize. Then run:")
    lines.append(f"#   pyobfus {scan_root} -o dist/ -c pyobfus.yaml")
    lines.append("#")
    lines.append(
        "# For AI coding assistants: the chosen preset already bundles "
        "framework-aware exclusions; adding entries below only refines on top."
    )
    lines.append("")

    # Config body
    lines.append("obfuscation:")
    lines.append("  # Preset selection")
    lines.append(f"  #   suggested based on detected frameworks: {preset}")
    lines.append(f"  #   alternatives: safe, balanced, aggressive, fastapi, django, flask,")
    lines.append(f"  #                 pydantic, click, sqlalchemy")
    lines.append(f"  preset: {preset}")
    lines.append("")

    lines.append("  # File patterns to skip (glob). Preset adds framework defaults;")
    lines.append("  # entries here extend that list.")
    lines.append("  exclude_patterns:")
    for pattern in excludes:
        lines.append(f"    - {_yaml_str(pattern)}")
    lines.append("")

    lines.append("  # Names to preserve (add your public API entry points here).")
    lines.append("  # Preset already excludes framework-managed symbols.")
    lines.append("  exclude_names: []")
    lines.append("")

    lines.append("  # Keep parameter names intact so keyword arguments survive obfuscation.")
    lines.append("  # Framework presets enable this automatically.")
    lines.append("  preserve_param_names: true")
    lines.append("")

    lines.append("  # Remove docstrings (framework presets keep them by default).")
    lines.append("  remove_docstrings: false")

    return "\n".join(lines) + "\n"


def _yaml_str(value: str) -> str:
    """Quote a string for YAML only when needed (glob patterns are safe unquoted
    but we always quote for consistency and to avoid YAML parser surprises)."""
    return '"' + value.replace('"', '\\"') + '"'
