"""Present statement locations without reconstructing source text."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any, Dict, List

if TYPE_CHECKING:
    from pyobfus.core.mapping import ObfuscationMapping

_FRAME = re.compile(
    r'^(?P<indent>[ \t]*)File "(?P<path>[^"\r\n]+)", line (?P<line>[0-9]+), in (?P<name>[^\r\n]+)$'
)


def restore_trace(mapping: ObfuscationMapping, trace: str) -> Dict[str, Any]:
    """Restore standard CPython frames, preserving excerpts and output paths."""
    frames: List[Dict[str, Any]] = []
    output: List[str] = []
    excerpt_prefix = None
    for text in trace.splitlines(keepends=True):
        body = text.rstrip("\r\n")
        ending = text[len(body) :]
        match = _FRAME.fullmatch(body)
        if match is None:
            if excerpt_prefix is not None and body.startswith(excerpt_prefix):
                output.append(text)
            else:
                excerpt_prefix = None
                output.append(mapping.unmap_text(text))
            continue
        path = match["path"]
        line = int(match["line"])
        location = mapping.resolve_location(path, line)
        status = location.status if location else "unmapped"
        frames.append(
            {
                "obfuscated_file": path,
                "obfuscated_line": line,
                "original_file": location.source if location and status == "mapped" else None,
                "original_line": location.line if location and status == "mapped" else None,
                "status": status,
            }
        )
        name = mapping.unmap_text(match["name"])
        if status == "mapped":
            assert location is not None
            body = (
                f'{match["indent"]}File "{location.source}", line {location.line}, in {name}'
                f"  [obfuscated: {path}:{line}]"
            )
        else:
            body = f'{match["indent"]}File "{path}", line {line}, in {name}'
            if status == "generated":
                body += "  [generated by pyobfus]"
        output.append(body + ending)
        excerpt_prefix = match["indent"] + "  "

    usable = [record.get("lines") is not None for record in mapping.files.values()]
    if not any(usable):
        line_map = "absent"
        hint = (
            "Names use the pre-obfuscation identifiers; line numbers still refer to the "
            "obfuscated output. Rebuild and save a mapping with pyobfus > 0.6.1 "
            "(a release with line-map support) to restore original files and lines. "
            "Builds with disabled line tables must use a supported Community build path."
        )
    else:
        partial = not all(usable) or any(frame["status"] == "unmapped" for frame in frames)
        line_map = "partial" if partial else "available"
        hint = (
            "Mapped frame files and line numbers refer to the original source at "
            "statement-level precision; the obfuscated locations are retained for comparison. "
            "Generated frames retain their output locations."
        )
        if partial:
            hint += (
                " Unresolved frames retain obfuscated locations; line restoration is incomplete."
            )
    hint += (
        " Code excerpts and caret indicators are unchanged obfuscated code, not original source."
    )
    return {
        "unmapped_trace": "".join(output),
        "frames": frames,
        "line_map": line_map,
        "ai_hint": hint,
    }
