"""Present statement locations without reconstructing source text."""

from __future__ import annotations

import re
from collections import Counter
from typing import TYPE_CHECKING, Any, Dict, List, Tuple

if TYPE_CHECKING:
    from pyobfus.core.mapping import ObfuscationMapping

_FRAME = re.compile(
    r'^(?P<indent>[ \t]*)File "(?P<path>[^"\r\n]+)", line (?P<line>[0-9]+), in (?P<name>[^\r\n]+)$'
)


def restore_trace(mapping: ObfuscationMapping, trace: str) -> Dict[str, Any]:
    """Restore names and frames belonging to the inferred deployment root."""
    from pyobfus.core.mapping import _path_parts

    def deployment_root(path: str, key: str) -> Tuple[bool, Tuple[str, ...]]:
        # Keep absolute and relative prefixes distinct; normalize Windows drives.
        return (path.startswith(("/", "\\")), tuple(_path_parts(path)[: -len(_path_parts(key))]))

    votes: Counter[Tuple[bool, Tuple[str, ...]]] = Counter()
    for text in trace.splitlines():
        match = _FRAME.fullmatch(text)
        if match is not None:
            key = mapping._match_file_path(match["path"])
            if key is not None:
                votes[deployment_root(match["path"], key)] += 1
    winners = [root for root, count in votes.items() if count == max(votes.values())]
    root = winners[0] if len(winners) == 1 else None
    tied = len(winners) > 1
    frames: List[Dict[str, Any]] = []
    output: List[str] = []
    for text in trace.splitlines(keepends=True):
        body = text.rstrip("\r\n")
        ending = text[len(body) :]
        match = _FRAME.fullmatch(body)
        if match is None:
            # Name restoration retains the 0.6.1 whole-text behavior. Indicator
            # lines contain no names and keep their original columns/endings.
            output.append(mapping.unmap_text(text))
            continue
        path = match["path"]
        line = int(match["line"])
        key = mapping._match_file_path(path)
        rejected = key is not None and (root is None or deployment_root(path, key) != root)
        location = None if rejected else mapping.resolve_location(path, line)
        status = location.status if location else "unmapped"
        frames.append(
            {
                "obfuscated_file": path,
                "obfuscated_line": line,
                "original_file": location.source if location and status == "mapped" else None,
                "original_line": location.line if location and status == "mapped" else None,
                "status": status,
            }
        )
        name = mapping.unmap_text(match["name"])
        if status == "mapped":
            assert location is not None
            body = (
                f'{match["indent"]}File "{location.source}", line {location.line}, in {name}'
                f"  [obfuscated: {path}:{line}]"
            )
        elif not rejected:
            body = f'{match["indent"]}File "{path}", line {line}, in {name}'
            if status == "generated":
                body += "  [generated by pyobfus]"
        output.append(body + ending)

    usable = [record.get("lines") is not None for record in mapping.files.values()]
    if not any(usable):
        line_map = "absent"
        hint = (
            "Names use the pre-obfuscation identifiers; line numbers still refer to the "
            "obfuscated output. Rebuild and save a mapping with pyobfus > 0.6.1 "
            "(a release with line-map support) to restore original files and lines. "
            "Builds with disabled line tables must use a supported Community build path."
        )
    else:
        partial = not all(usable) or any(frame["status"] == "unmapped" for frame in frames)
        line_map = "partial" if partial else "available"
        hint = (
            "Mapped frame files and line numbers refer to the original source at "
            "statement-level precision; the obfuscated locations are retained for comparison. "
            "Generated frames retain their output locations."
        )
        if partial:
            hint += (
                " Unresolved frames retain obfuscated locations; line restoration is incomplete."
            )
    if tied:
        hint += (
            " Cannot determine the deployment root: frame support is tied; frames are unresolved."
        )
    hint += (
        " Code excerpts are artifact code with names restored; column positions and caret "
        "indicators follow the artifact text and do not correspond to original source."
    )
    return {
        "unmapped_trace": "".join(output),
        "frames": frames,
        "line_map": line_map,
        "ai_hint": hint,
    }
